BrightspaceHypermediaComponents/siren-sdk

es6/Entity.js
es6/EntityFactory.js
mixin/entity-mixin.js

Basically added the JSDocs comments.
Fixed a missed decompose. We are zombie free!

Add JSDocs comments.

---

.eslintignore
.eslintrc.json
.travis.yml
es6/Entity.js
es6/EntityFactory.js
mixin/entity-mixin.js
package-lock.json
package.json
polymer.json
test/index.html
test/skeleton-test.html
wct.conf.json

Has the changes from https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/3

Test skeleton and linting repo setup

---

es6/Entity.js

Update entity import.

---

es6/Entity.js
package-lock.json
package.json

Added the entity store as a dependancy
Allows us to check if the entity has a class

Add Has Class

---

es6/Entity.js
test/entity.html
test/index.html
test/nothing-entity.js

Very rough fix, but good enough for now i think.  There's some edgecases where it won't work exactly like new.target, but i'm not sure that matters.  If someone goes beyond the immediate safety we've provided they will have to accept the risks

Ie11 compatibility

---

src/organizations/OrganizationEntity.js
src/root/root.js
test/index.html
test/root/root.html
test/root/root.js

Adds:
- Organization homepage link to org entity (sub entity is relative which won't work for consortium)
- Link root > organization

Organization entity on root

---

src/sequences/SequenceEntity.js
test/SequenceEntity/SequenceEntity.js
test/SequenceEntity/data/sequenceRoot.js

Order of these sub-entities matter. 
Add the ordering to sub-entities responses.
See use: https://github.com/BrightspaceHypermediaComponents/sequences/pull/139

index sequence responses

---

package.json
src/sequences/SequenceEntity.js
test/SequenceEntity/SequenceEntity.js
test/SequenceEntity/data/sequenceRoot.js

```
class: ["completion", "incomplete"]
properties: {completed: 0, total: 1, optionalViewed: 0, optionalTotal: 5}
rel: ["item", "https://api.brightspace.com/rels/completion"]
```
This is the sub-entity that I am reading.

Let us get completion data! (From Sequences!)

---

src/sequences/SequenceEntity.js
test/SequenceEntity/SequenceEntity.js

So changed include that there should only be one organization href per activity.
There is only one Activity per Activity-Sequence

Update how to get Org Href from sequence

---

src/sequences/SequenceEntity.js
test/SequenceEntity/data/sequenceRoot.js

completed!

---

src/consortium/ConsortiumRootEntity.js
test/consortium/ConsortiumRootEntity.html
test/consortium/ConsortiumRootEntity.js
test/consortium/ConsortiumTokenCollectionEntity.js
test/index.html
test/mixin/entity-mixin-test.js
test/root/root.js

There's a root in between the collection now. Updating the sdk with the new entity

Consortium root

---

src/organizations/OrganizationEntity.js

Add classes to organization

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.js

Goes with https://github.com/BrightspaceHypermediaComponents/activities/pull/380

US110193 add function to determine if editing name is permitted

---

src/activities/ActivityUsageCollectionEntity.js
test/activities/ActivityUsageCollectionEntity.html
test/activities/ActivityUsageCollectionEntity.js
test/activities/data/collection.js
test/index.html

- Add the initial `ActivityUsageCollectionEntity` to allow the collected items and their corresponding activity usage hrefs to be accessed.

Initial Activity Collection Entities

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

[US111291](https://rally1.rallydev.com/#/39602890252d/detail/userstory/342352818840)

adding edit link to activity usage

---

src/hypermedia-constants.js
src/organizations/OrganizationAvailabilityEntity.js
src/organizations/OrganizationAvailabilitySetEntity.js
test/index.html
test/organizations/OrganizationAvailabilityEntity.html
test/organizations/OrganizationAvailabilityEntity.js
test/organizations/OrganizationAvailabilitySetEntity.html
test/organizations/OrganizationAvailabilitySetEntity.js
test/organizations/data/OrganizationAvailabilityEntity.js
test/organizations/data/OrganizationAvailabilitySetEntity.js

To be used by organizations: https://github.com/BrightspaceHypermediaComponents/organizations/pull/132

Initial commit for OrganizationAvailabilitySet and OrganizationAvailability

---

src/es6/SirenAction.js
src/organizations/OrganizationAvailabilityEntity.js

Calls the `polymer-siren-behaviors` `remove` function: https://github.com/Brightspace/polymer-siren-behaviors/pull/59/files#diff-b0c1bbfcefba9a380d3371ab1b1c3bacR265

Remove item from Entity Store if response body is empty

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

[US109698](https://rally1.rallydev.com/#/detail/userstory/332018306084?fdp=true)
This PR adds the assignment release conditions stuff, but this time to the activity usage.

US109698 Add activity usage release conditions dialog opener

---

src/activities/ActivityUsageEntity.js
src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

[US111919](https://rally1.rallydev.com/#/detail/userstory/350454972296?fdp=true)
This PR adds the assignment turnitin dialog stuff. Also, apparently `this._entity` can be weird, so I added a check for that back into the release conditions dialog stuff too.

US111919 Add assignments turnitin dialog opener

---

src/es6/SirenAction.js
src/organizations/OrganizationCollectionEntity.js
src/organizations/OrganizationEntity.js

1. This pull request adds an `OrganizationCollectionEntity` to represent the response returned from the `OrganizationsController` with support for sorting and paging.
2. Fixed a bug in `SirenAction` where hidden fields are dropped for actions using `GET`.

Add OrganizationCollectionEntity

---

src/activities/ActivityUsageCollectionEntity.js
src/es6/Entity.js
src/es6/EntityFactory.js

Allows us to remove an item from the collection

Remove Item from collection

---

src/activities/ActionCollectionEntity.js

Support ActionCollection response for Learning Paths.

add ActionCollectionEntity

---

src/enrollments/EnrollmentCollectionEntity.js

Required for the My Learning - See All page to access the information of and display each enrollment entity to the user.
Mirrors the similarly-named function in ActivityUsageCollectionEntity,

Added onEnrollmentsChange function to access enrollment entities

---

src/activities/ActionCollectionEntity.js
src/es6/Entity.js
src/es6/EntitySirenProperties.js
src/es6/SelflessEntity.js

Used when there is a sub-entity with no self attribute. Allows the sub-entities of these have a parent that will clean them up.

Selfless Entity

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

[US112497](https://rally1.rallydev.com/#/detail/userstory/356251784900?fdp=true)
This PR adds the siren stuff for anonymous marking in fu-ace.

US112497 Add anonymous marking

---

src/activities/AttachmentCollectionEntity.js

Video note attachments work almost exactly the same as link attachments - we just provide a name and href.

US111908 Add video note functionality

---

src/enrollments/EnrollmentCollectionEntity.js

My Learning widget needed an href to get to /le/mylearning, which I added here

support for my-learning href, used by learning widget

---

src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.js

added new setDates function to call combined dates action. setDates is then used in the overall save function.

US113165 Integrate with aggregate save dates action

---

src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.js

Calling `entity.validate(activity)` will perform the dates update action, but with the additional `validateOnly` field set to true so the back-end will only validate, not persist.

Add validation method to ActivityUsageEntity and hook it up to dates

---

src/activities/Association.js
src/hypermedia-constants.js

Add the action for deleting an association

Add delete association

---

src/activities/ActivityUsageEntity.js
src/activities/conditions/LegacyConditions.js
src/es6/Entity.js
src/hypermedia-constants.js

[US109699](https://rally1.rallydev.com/#/detail/userstory/332018308528?fdp=true)
[US112831](https://rally1.rallydev.com/#/detail/userstory/360464559620?fdp=true)
[US112832](https://rally1.rallydev.com/#/detail/userstory/360464569172?fdp=true)
[US112859](https://rally1.rallydev.com/#/detail/userstory/360697030860?fdp=true)
[US113905](https://rally1.rallydev.com/#/detail/userstory/371431522876?fdp=true)
prereq for all of those ⬆️ 
This PR adds hypermedia for using legacy release conditions in the assignments editor. Since this is still quite expedient, I'm prefixing everything with `--legacy-` so that I don't steal any good names for this bridge version.

Release conditions (Part 1)

---

src/activities/conditions/LegacyConditions.js
src/hypermedia-constants.js

[US112831](https://rally1.rallydev.com/#/detail/userstory/360464559620?fdp=true)
[US112859](https://rally1.rallydev.com/#/detail/userstory/360697030860?fdp=true)
[US113905](https://rally1.rallydev.com/#/detail/userstory/371431522876?fdp=true)
prereq for all of those ⬆️ 
This PR adds hypermedia for condition set operators.
[⬅ Part 1](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/135)

Release conditions (Part 2)

---

src/activities/conditions/LegacyConditions.js

Should return something that loosely resembles an array for a "default return," whoops!

Fix retval

---

src/activities/assignments/AssignmentEntity.js

[US114431](https://rally1.rallydev.com/#/detail/userstory/375347576500?fdp=true)
This PR adds anonymous marking mobx saving.

US114431 Add anonymous marking mobx

---

src/activities/assignments/AssignmentEntity.js

[US114432](https://rally1.rallydev.com/#/detail/userstory/375348467832?fdp=true)
This PR adds annotations mobx saving.

US114432 Add annotations mobx

---

src/activities/assignments/AssignmentEntity.js

[US113669](https://rally1.rallydev.com/#/detail/userstory/368261329852?fdp=true)
This PR adds Turnitin hypermedia.

US113669 Add turnitin hypermedia

---

docs/AssignmentEntity.html
docs/activities_assignments_AssignmentEntity.js.html
src/activities/assignments/AssignmentEntity.js

Reverts BrightspaceHypermediaComponents/siren-sdk#157
need to remove this from the MobX store

Revert "Removed the completionTypeOptions method from AssignmentEntity"

---

.gitignore
src/activities/assignments/AssignmentEntity.js

https://trello.com/c/wdprzZ76/145-do-not-popup-the-discard-popup-if-user-has-not-made-any-changes-before-they-pressed-cancel-or-back

fix equals logic

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.js
test/activities/assignments/data/EditableAssignment.js

It is EOD. I am checking in the code before I leave. 
WIP: needs to add update unit tests.

fix missing fields in equals comparison logic

---

src/activities/Associations.js
src/hypermedia-constants.js

Add create potential association action

Add action to create potential association

---

src/activities/ActivityUsageEntity.js
src/competencies/CompetenciesEntity.js
src/hypermedia-constants.js
test/activities/ActivityUsageEntity.js
test/activities/data/ActivityUsageEntity.js
test/competencies/CompetenciesEntity.html
test/competencies/CompetenciesEntity.js
test/competencies/data/CompetenciesEntity.js

To be used by the legacy competencies integration in the activity editor in d2l-activities

US115941 Legacy competencies entity

---

src/activities/assignments/AssignmentEntity.js

https://rally1.rallydev.com/#/29180338367d/detail/defect/392934610756

DE39197 - Fix submissions/completions triggering dirty

---

src/activities/ActivitySpecialAccessEntity.js
src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js
test/activities/ActivitySpecialAccessEntity.html
test/activities/ActivitySpecialAccessEntity.js
test/activities/ActivityUsageEntity.js
test/activities/data/ActivitySpecialAccessEntity.js
test/activities/data/ActivityUsageEntity.js
test/index.html

https://rally1.rallydev.com/#/29180338367d/detail/userstory/397387989372

US117523 - Add SpecialAccessEntity

---

src/activities/Association.js
src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

This PR adds retrieval and saving of the default scoring rubric for an assignment.
This is not the best solution but due to the time constraint we are going with the solution and will come back and clean it up with the deferred rubric save work.

US109625 Default scoring rubric

---

src/activities/ActivityUsageEntity.js

see https://github.com/BrightspaceHypermediaComponents/activities/pull/1137

initialize scoreOutOf to empty when comparing

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/detail/userstory/438844242444?fdp=true

US120984 - Quiz Disable Right Click

---

src/activities/ActivityUsageEntity.js
src/alignments/AlignmentsHierarchicalEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F455318565812%2Ftasks
Supports https://github.com/BrightspaceHypermediaComponents/activities/pull/1189

Support hierarchical alignments entity from activity usage

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

[US121856](https://rally1.rallydev.com/#/detail/userstory/449829054032?fdp=true): [ui] Summarizer: disable right click

US121856 Quiz password ui

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

[US120986](https://rally1.rallydev.com/#/detail/userstory/438844250288?fdp=true): [ui] Add block alerts checkbox

US120986 Quizzes: Add support for block alerts/disable pager and alerts

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/userstory/458770937868

US122653 Quizzing prevent moving backwards

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

[US122651](https://rally1.rallydev.com/#/detail/userstory/458770910924/tasks?fdp=true): [ui] Shuffle questions

US122651 Quizzes: Add support for shuffle questions

---

src/activities/quizzes/QuizEntity.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

Part of https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F459179692392

US122707 Get preview href

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F459179692392

Added logic to check if a quiz can be previewed

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F460656857624

US123027 Automatic grade attempt

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F458494147960&fdp=true?fdp=true

US122636 - Delete quiz on cancel

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/ForkedWorkingCopyQuiz.js
test/activities/quizzes/data/WorkingCopyQuiz.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478606416460
This is the UI part of the API changes in US122604

US123692 - Add functions for calling working copy related quiz actions

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F413008461552&fdp=true

Mdulat iwallace/us119424 UI quiz description field

---

src/activities/quizzes/AttemptsEntity.js
src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/AttemptsEntity.html
test/activities/quizzes/AttemptsEntity.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/AttemptsEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js
test/index.html

Created a new AttemptsEntity class and wrote some basic tests
[US123706](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true): [ui] Attempts: Conditions entities
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true

US123706 added AttemptsEntity and basic tests

---

src/hypermedia-constants.js

https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fuserstory%2F459574106476&fdp=true?fdp=true
https://rally1.rallydev.com/#/357251704080d/workviews/collection?detail=%2Fuserstory%2F424772018272&fdp=true&itemRef=%2Fhierarchicalrequirement%2F402598668904&previousTokens=%2F357251704080d%2Fcustom%2F367300408400%3F&previousTokens=%2F357251704080d%2Fworkviews%2Fcollection%3FitemRef%3D%252Fhierarchicalrequirement%252F412067419092%26project%3D%252Fproject%252F357251704080%26ref%3D%252Fhierarchicalrequirement%252F412067419092%26relationship%3Dchildren&project=%2Fproject%2F357251704080&ref=%2Fhierarchicalrequirement%2F402598668904&relationship=children&fdp=true?fdp=true
https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fuserstory%2F459454738300&fdp=true? …

feat: Add new activities constants.

---

src/hypermedia-constants.js

https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fuserstory%2F480453371564&fdp=true&fdp=true?fdp=true

feat: US123834: Add my organization activity rels.

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F479012712268&fdp=true
Adds this read-only property of the description entity (whether description-is-displayed class exists)

feat: US123717 add descriptionIsDisplayed

---

src/activities/quizzes/QuizEntity.js
src/activities/quizzes/ipRestrictions/QuizIpRestrictionsEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/ipRestrictions/EditableEntity.js
test/activities/quizzes/data/ipRestrictions/NonEditableEntity.js
test/activities/quizzes/ipRestrictions/QuizIpRestrictionsEntity.html
test/activities/quizzes/ipRestrictions/QuizIpRestrictionsEntity.js
test/index.html

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F465115111280
Start of siren-sdk work for IP restrictions. This is pretty rough. Will need to add tests etc but wanted to get some feedback on the general approach.

Added support for IP restrictions

---

src/activities/quizzes/ipRestrictions/QuizIpRestrictionsEntity.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F465115111280
We actually don't need to specify these fields as they are provided by the action.

Cleaned up IP restrictions delete

---

test/activities/quizzes/QuizEntity.js

feat: US123275 Quiz Header.

---

src/activities/quizzes/timing/QuizTimingEntity.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F464625055264%2Ftasks

US123360 - rename because the function doesn't toggle

---

src/activities/quizzes/timing/QuizTimingEntity.js
test/activities/quizzes/timing/QuizTimingEntity.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F464625055264%2Ftasks

US123360 - Quiz Timing read-only view

---

src/activities/quizzes/attempts/QuizAttemptsEntity.js

[US123706](https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F478977336380%2Ftasks&fdp=true?fdp=true): [ui] Attempts: Conditions entities

US123706 Quizzes: RIO siren fixes

---

src/activities/quizzes/attempts/QuizAttemptsEntity.js

[US123706](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true): [ui] Attempts: Conditions entities

US123706 Quizzes: Fix overall grade calculation logic

---

src/activities/quizzes/attempts/QuizAttemptsEntity.js

fix: Add note about RIO flag

---

src/activities/quizzes/attempts/QuizAttemptsEntity.js
src/hypermedia-constants.js
test/activities/quizzes/attempts/QuizAttemptsEntity.js
test/activities/quizzes/data/attempts/EditableEntity.js
test/activities/quizzes/data/attempts/NonEditableEntity.js

[US123706](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true): [ui] Manage Attempts (Attempts allowed, RIO, Attempt conditions)

US123706 Quizzing: Attempt Conditions entity

---

src/activities/quizzes/attempts/QuizAttemptsEntity.js

[US123706](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true): [ui] Manage Attempts (Attempts allowed, RIO, Attempt conditions)

US123706 Quizzes: Attempt Conditions - handle deletes on min and/or max

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F505562070580&fdp=true

add functions to enable checkout of activity usage

---

src/activities/content/ContentLTILinkEntity.js
src/activities/content/ContentModuleEntity.js
src/activities/content/ContentWebLinkEntity.js
test/activities/content/ContentLTILinkEntity.js
test/activities/content/ContentWebLinkEntity.js

[In this PR](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/304), I noticed that some of the tests needed to be updated, and @ianlaidlaw noticed that some of the return definitions weren't accurate. This PR updates both.

Update tests and return types

---

src/activities/CategoriesEntity.js
src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js
test/activities/CategoriesEntity.html
test/activities/CategoriesEntity.js
test/activities/data/EditableCategories.js
test/activities/data/EmptyCategories.js
test/activities/data/NonEdtiableCategories.js
test/activities/data/NonSelectedCategories.js
test/index.html

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F519563556284
Added methods to siren-sdk for interacting with categories.

Us126777/add existing categories to UI

---

src/activities/quizzes/QuizEntity.js

https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F516914643580&fdp=true?fdp=true

Feat:  US126437 Adding alert when a quiz header is turned visible.

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F502525662860%2Ftasks&fdp=true?fdp=true

feat:  US125269 Adding footer to siren.

---

src/activities/quizzes/QuizEntity.js
src/activities/quizzes/types/ActivityTypeEntity.js
src/hypermedia-constants.js

Used by https://github.com/BrightspaceHypermediaComponents/activities/pull/1726
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F604399313080

US128126 Support accessing supported quiz question types

---

src/activities/associateGrade/GradeCategoryLinkedEntity.js

https://rally1.rallydev.com/#/29180338367ud/dashboard?detail=%2Fuserstory%2F505558523792&fdp=true?fdp=true

Fix GradeCategoryLinkedEntity get Href

---

src/activities/associateGrade/AssociateGradeEntity.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F505559228552%2Ftasks&fdp=true&itemRef=%2Fhierarchicalrequirement%2F505559228552&previousTokens=%2F29180338367ud%2Fcustom%2F486232622040%3Fdetail%3D%252Fuserstory%252F505559228552&project=%2Fproject%2F29180338367&ref=%2Fhierarchicalrequirement%2F505559228552&relationship=tasks

feat: US125504 add setGradeType function to associate-grade

---

src/activities/GradeCandidateEntity.js
src/activities/associateGrade/GradeCategoryLinkedEntity.js
test/activities/GradeCandidateEntity.js
test/activities/associateGrade/GradeCategoryLinkedEntity.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F601489857733&expandApp=486232622048&fdp=true?fdp=true

US129035 - Call action to PATCH grade / category change

---

.github/workflows/release.yml
src/activities/content/ContentLTILinkEntity.js
src/activities/content/ContentLTILinkFrameOptionsEntity.js
src/hypermedia-constants.js
test/activities/content/ContentLTILinkFrameOptionsEntity.html
test/activities/content/ContentLTILinkFrameOptionsEntity.js
test/activities/content/data/TestContentLTILinkFrameOptionsEntity.js
test/index.html

[DE43998](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F601841380817&fdp=true): [cert] LTI page - Add link to LTI link entity that will check X-Frame-Options header
Backport of https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/337 for 20.21.7.

DE43998: [cert] LTI - Add LinkFrameOptionsEntity

---

src/activities/content/ContentLTILinkFrameOptionsEntity.js

Fixes the return definition to be accurate to the method.

Change return type from string to boolean

---

src/activities/ActivityUsageEntity.js

🎉 
https://rally1.rallydev.com/#/10235005524d/dashboard?detail=%2Fuserstory%2F505562087036&fdp=true?fdp=true

US122507 - Enable activity CheckIn

---

src/activities/ActivityUsageEntity.js

Fixes https://trello.com/c/JVZtua6s/393-creating-new-grade-creates-duplicate-numeric-grade-item
Goes with https://github.com/BrightspaceHypermediaComponents/activities/pull/1830

fix: duplicate grade created

---

src/activities/content/ContentFileEntity.js

Follow-up to https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/355 to have automated release happen.

Minor change to comment

---

src/activities/assignments/AssignmentEntity.js

https://trello.com/c/A61OrkUc/296-on-assignment-save-patch-api-on-folder-is-always-executed-even-when-there-are-no-changes-request-body-includes-notificationemail

Stop sending Assignment Patch when nothing has changed

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

[US128833 - [Restrict File Ext][UI] Add new dropdown for the restrict file extension options](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F600937249791)
Used by [https://github.com/BrightspaceHypermediaComponents/activities/pull/1898](https://github.com/BrightspaceHypermediaComponents/activities/pull/1898)

US128833 - adding support for update-allowable-filetype action for assignments

---

src/activities/assignments/AssignmentEntity.js

https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F600937250069

feat: add custom allowable filetypes functionality

---

src/hypermedia-constants.js
src/rubrics/RubricEntity.js

In support of https://github.com/BrightspaceHypermediaComponents/activities/pull/1946
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F607223441505

DE44886 Create RubricEntity class

---

test/activities/ScoringEntity.html
test/activities/ScoringEntity.js
test/activities/data/ScoringEntity.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F608101223745&fdp=true

fix: add unit tests for new ScoringEntity

---

src/activities/ScoringEntity.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F608101223185&fdp=true

fix: dirty check changes to score-out-of

---

src/activities/ScoringEntity.js
test/activities/ScoringEntity.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F606249971567&fdp=true

fix: US130775 use gradeMaxPoints for GradeOutOf value

---

src/activities/associateGrade/AssociateGradeEntity.js
test/activities/associateGrade/AssociateGradeEntity.js
test/activities/associateGrade/data/NewGradeNumericOnlyEditable.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F606249971567%2Ftasks&fdp=true
Allows us to see if a NewGrade can only have numeric types

feat: US130775 distinguish types that have only numeric grade types

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js

https://rally1.rallydev.com/#/?detail=/userstory/608889244131&fdp=true

US131582 - Get submission views href from quiz entity

---

src/activities/quizzes/submissionViews/QuizSubmissionViewsEntity.js
src/hypermedia-constants.js
test/activities/quizzes/data/submissionViews/SubmissionViewsEntity.js
test/activities/quizzes/submissionViews/QuizSubmissionViewsEntity.html
test/activities/quizzes/submissionViews/QuizSubmissionViewsEntity.js
test/index.html

Add file for `QuizSubmissionViewsEntity` and add a test file.
My story doesn't include checking for the `add` action, but I included that so that the test and entity file aren't blank.
https://rally1.rallydev.com/#/?detail=/userstory/608889244131&fdp=true

US131582 - Add initial commit for `QuizSubmissionViewsEntity`

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js
src/activities/quizzes/submissionViews/QuizSubmissionViewsEntity.js
src/hypermedia-constants.js
test/activities/quizzes/data/submissionViews/SubmissionViewEntity.js
test/activities/quizzes/submissionViews/QuizSubmissionViewEntity.html
test/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js
test/activities/quizzes/submissionViews/QuizSubmissionViewsEntity.js
test/index.html

https://rally1.rallydev.com/#/?detail=/userstory/608889244131&fdp=true

US131582 - Add entity for SubmissionView and getting submission view sub-entities

---

src/activities/content/ContentMediaFileEntity.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

- [TA158697](https://rally1.rallydev.com/#/?detail=/task/612430665105&fdp=true): Add properties onto HM response
This PR has the new properties from the LMS PR linked below
- LMS: https://github.com/Brightspace/lms/pull/15425
- Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2088

TA158697 > media file hm properties

---

src/activities/content/ContentMediaFileEntity.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

Same PR as https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/404 where I forgot the semver

TA158697 media file hm properties

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js
test/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F611715477831

US132834  - Get attemptRestrictions options from action value

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js

https://rally1.rallydev.com/#/?detail=/userstory/602632659323&fdp=true

feat: US129509 add syncGradebookDefault functions

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/610534919701&fdp=true

US132398 - SubView questions checkboxes call PATCH

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js
test/activities/quizzes/data/submissionViews/SubmissionViewEntity.js
test/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/610534913293&fdp=true

Fix submission view to get both html and text message properties

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

I was getting this console error because it was trying to read properties of undefined:

fix: read property of undefined

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js
test/activities/quizzes/data/submissionViews/SubmissionViewEntity.js
test/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/613849027377&fdp=true

US133503 - check for ip-restrictions sub-entity

---

src/activities/content/ContentMediaFileEntity.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

- [TA158697](https://rally1.rallydev.com/#/?detail=/task/612430665105&fdp=true): Add properties onto HM response
Add a new property for the media file name to easily support content service media files and manage files files.

TA158697 (Part 2): Add mediaFileName property

---

src/activities/content/ContentMediaFileEntity.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/609662239823&fdp=true
activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2133
LMS: [WIP PR](https://github.com/Brightspace/lms/compare/nabrown/TA158697-audio-video-hm-properties...dacho/nabrown/TA158697-audio-video-hm-properties?expand=1)

Add properties for Content Service to ContentMediaFileEntity

---

src/activities/quizzes/submissionViews/QuizSubmissionViewsEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/610534917433&fdp=true

US132396 - Add additional view

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

Fixed an issue with submission views siren-sdk, part of user story US132834 (fixed min/max grade API call)

siren-sdk fixes for min-max grade, part of US132834

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/610534919701&fdp=true

US132398 - Fix set show standards

---

src/activities/content/ContentMediaFileEntity.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

Related LE PR that adds the value: https://github.com/Brightspace/lms/pull/16395

Add topicId used for content service to ContentMediaFileEntity

---

src/activities/ScoringEntity.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fdefect%2F615608209587%2Ftasks&fdp=true
cert fix

fix: DE46108 cert fix

---

src/activities/ScoringEntity.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fdefect%2F615608209587%2Ftasks&fdp=true
hotfix

fix: DE46108 hotfix

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

US133817: 
- Small siren-sdk change to check for the attempts restrictions subentity. 
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F616680095557

feat: US133817 add attempt restrictions

---

src/activities/quizzes/submissionViews/QuizSubmissionViewEntity.js

Small change for https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F616680095557
Changed subentity reference from grade to attempt restrictions.

Fix: US133817, change from grade to attempt restrictions subentity

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/?detail=/userstory/492774206184&fdp=true

feat: US124659 add functions for quiz completion tracking

---

package.json
src/activities/content/ContentEntity.js
src/activities/content/ContentImportedScormActivityEntity.js
src/hypermedia-constants.js

- [US134135](https://rally1.rallydev.com/#/?detail=/userstory/618457828675&fdp=true): SCORM - Properties can be edited and saved
Adding FACE support for imported SCORM
1. LMS: https://github.com/Brightspace/lms/pull/17714
2. Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2291

US134135: FACE Support for Imported SCORM

---

src/activities/associateGrade/AssociateGradeEntity.js

US134750: SCORM - Push Existing Scores to new Grade Item does the action

---

package.json
test/activities/ActivityUsageEntity.js
test/activities/GradeCandidateCollectionEntity.js
test/consortium/ConsortiumTokenCollectionEntity.js
test/es6/EntityFactory.js
test/es6/SirenActionTest.js
test/helpers/StateTree.js
test/mixin/entity-mixin-test.js
test/mixin/simple-entity-mixin-test.js
test/organizations/OrganizationAvailabilityEntity.js
test/organizations/OrganizationAvailabilitySetEntity.js
test/root/root.js

Bumping to sinon 13 (compatible with open-wc/testing 2 and 3)

Bump test dependencies in preparation for lit 2

---

README.md

[US136096](https://rally1.rallydev.com/#/?detail=/userstory/626871691749&fdp=true): [UCE] existing completion summary api data source

feat: US136096 adding ActivityEvaluationStatusEntity

---

src/activities/content/ContentImportedScormActivityEntity.js

Backport of https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/458
Rally ticket [DE47321](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F627185737859&fdp=true)

[CERT] DE47321: Add embedUrl to imported SCORM entity

---

src/activities/content/ContentImportedScormActivityEntity.js

Rally ticket [DE47484](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F627957174891&fdp=true)
Backport of https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/461

[CERT] DE47484: Hide push to grades checkbox

---

test/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F621580285913

US134953 Added Tests for Has Attempts sub-entity

---

src/activities/content/ContentFileEntity.js

- [US137225](https://rally1.rallydev.com/#/?detail=/userstory/629906199455&fdp=true): Uploaded Files - Add Banner with File Name

US137225: Uploaded Files - Add Banner with File Name

---

package.json
src/activities/content/ContentFileEntity.js
src/hypermedia-constants.js

Adds the replace-file action.
lms: https://github.com/Brightspace/lms/pull/22587
activites: https://github.com/BrightspaceHypermediaComponents/activities/pull/2614
https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F512889833236&fdp=true

US126165: Add replace action for file activities

---

src/activities/AttachmentCollectionEntity.js
src/activities/content/ContentWebLinkEntity.js

[US138621](https://rally1.rallydev.com/#/520974201756d/iterationstatus?detail=%2Fuserstory%2F633260836465&fdp=true&view=3265e82f-7ab0-4a61-abd2-b40776bb4cb3)

US138621 - Add support for OneDrive LTI picker

---

README.md

Missed that the file I deleted was linked to from the README

docs: Remove Contributing section from README

---

src/activities/AttachmentCollectionEntity.js

[US138621](https://rally1.rallydev.com/#/520974201756d/iterationstatus?detail=%2Fuserstory%2F633260836465&fdp=true&view=3265e82f-7ab0-4a61-abd2-b40776bb4cb3)

US138621 - Add support for OneDrive LTI picker [20.22.6]

---

src/hypermedia-constants.js
src/organizations/OrganizationEntity.js

* [US137332](https://rally1.rallydev.com/#/?detail=/userstory/630193792697&fdp=true): Course Merge - API - GET Course List
* [US137345](https://rally1.rallydev.com/#/?detail=/userstory/630200747123&fdp=true): Course Merge - UI - Course Offering Information List
* https://github.com/Brightspace/lms/pull/24003
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/1

feat: Add organization ancestor links

---

src/hypermedia-constants.js
src/organizations/OrganizationEntity.js

Reverts BrightspaceHypermediaComponents/siren-sdk#491
* [US137332](https://rally1.rallydev.com/#/?detail=/userstory/630193792697&fdp=true): Course Merge - API - GET Course List
* [US137345](https://rally1.rallydev.com/#/?detail=/userstory/630200747123&fdp=true): Course Merge - UI - Course Offering Information List

Revert "Add organization ancestor links"

---

src/activities/quizzes/timing/QuizTimingEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/16349626795d/custom/260792024672?detail=%2Fuserstory%2F641503728563

US140625 Added isNoTimeLimit to QuizTimingEntity

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingEntity.js
src/ipsis/course-merge/CourseMergeOfferingListEntity.js
src/ipsis/course-merge/CourseMergeRootEntity.js

Rally: https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F630193792697

feat: Add new rels for IPSIS SIS Course Offering(s)

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingEntity.js
src/ipsis/course-merge/CourseMergeRootEntity.js

Reverts BrightspaceHypermediaComponents/siren-sdk#497

Revert "Revert "feat: Add new rels for IPSIS SIS Course Offering(s)""

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/431372673576d/iterationstatus?detail=%2Fuserstory%2F642211974203

US140951-TextFileSubmission-ShowAllowTextSubmission

---

src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F630202539309

feat: US137347 Course merge filters

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js
test/activities/discussions/data/NonEditableDiscussionTopic.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F641400889073
US140575: 
- Added siren-sdk class code to handle description (richtext and HTML). **TA165639** of US140575. 
- Added description cases to test file.

US140575: Topic description UI for FACE discussions. 

---

src/activities/ActivityUsageEntity.js

[US140600](https://rally1.rallydev.com/#/?detail=/userstory/641472138379&fdp=true)
Adding display in calendar fetch to be displayed with ActivityAvailabilityDates

Add displayInCalendar to ActivityUsageEntity

---

src/activities/discussions/DiscussionTopicEntity.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F641400889073 
Original PR: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/508 .
Cleaning up the siren-sdk code for update description.

US140575: Refactoring siren-sdk code. 

---

src/activities/discussions/DiscussionTopicEntity.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F641400889073%2Ftasks
Fix dirty check

US140575: Fix dirty check

---

src/activities/discussions/DiscussionTopicEntity.js

[US140926](https://rally1.rallydev.com/#/?detail=/userstory/642120419367&fdp=true): Sync title between new topic + new forum

US140926 Add discussion topic forum name sync logic

---

src/activities/ActivityUsageEntity.js

Part 1, passing in the value from editor into the action

Add DisplayInCalendar to the save dates action

---

package.json
src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F627721866839
Related PRs:
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/13
* https://github.com/Brightspace/lms/pull/25838

feat: US136498 - Add Search Action 

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js

[US140704](https://rally1.rallydev.com/#/?detail=/userstory/641659231455&fdp=true): Sync visibility between new topic + new forum

US140704 Add sync draft properties

---

src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

* https://rally1.rallydev.com/#/255540250444d/backlog?detail=%2Fuserstory%2F642767486081
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/17
Looking for initial feedback as I'm not sure I like this change as is.

fix: Updates to allow load more paging

---

docs/AssignmentEntity.html
docs/activities_assignments_AssignmentEntity.js.html
src/activities/assignments/AssignmentEntity.js
src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/assignments/data/EditableAssignment.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://rally1.rallydev.com/#/?detail=/userstory/644280021699&fdp=true

US142118 remove references to RichtextEditorConfig

---

src/activities/ActivityUsageEntity.js

Update to read from either names and will remove the old name in another PR

Reword dateType to availabilityType

---

src/activities/discussions/DiscussionForumEntity.js
src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js

[US142491](https://rally1.rallydev.com/#/?detail=/userstory/644998737805&fdp=true): [ui] Create choose forum dialog
[US141010](https://rally1.rallydev.com/#/?detail=/userstory/642314304651&fdp=true): [ui] Create new forum text
This let's us get the name of the topic's forum and add support for us to create a new forum as well.

US142491 Add siren Discussion Forum entity

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js

https://rally1.rallydev.com/#/?detail=/userstory/645373894667&fdp=true
Add has-posts to discussion topic entity

US142666 add hasPosts to discussion topic entity

---

src/activities/quizzes/timing/QuizTimingEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/643174099233&fdp=true
- Update the `enforcedTimeLimit()` method to accept a `data` argument, which when passed will be returned as a part of the resulting `enforcedTimeLimit` object.
- Do the same for `recommendedTimeLimit()` method.
This is similar to what the current `isTimingEnforced()` method does:
https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/5fbfa4185ee46c3c463fd111bbabe889b225e2fd/src/activities/quizzes/timing/QuizTimingEntity.js#L53-L57
This change shouldn't affect any current implementation as the current implementation doesn't call the `enforcedTImeLimit()` method with the `data` argument.
[US141391](https://rally1.rallydev.com/#/?detail=/userstory/643174099233&fdp=true): [UI] Quiz Edit Settings UI in FACE

Update `enforcedTimeLimit` method to accept a update value

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingEntity.js

Related PR:
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/28
Story:
* https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F630445451251

feat: US137419 - UI - Select course

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingEntity.js

Reverts BrightspaceHypermediaComponents/siren-sdk#522

Revert "feat: US137419 - UI - Select course"

---

src/hypermedia-constants.js

* [US138078](https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F631615262871)
- https://github.com/Brightspace/lms/pull/27180

fix: Fix action to be lower case

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js

[US140677](https://rally1.rallydev.com/#/?detail=/userstory/641654621783&fdp=true)

feat: US140677 Add topic delete entities and actions

---

src/activities/quizzes/timing/QuizTimingEntity.js
src/hypermedia-constants.js

Story: [US141391](https://rally1.rallydev.com/#/?detail=/userstory/643174099233&fdp=true): [UI] Quiz Edit Settings UI in FACE
Task: [TA166882](https://rally1.rallydev.com/#/?detail=/task/645922888849&fdp=true): Update the Manage Timing dialog with the new design and functionalities
- Added functions to handle getting/updating the new time limit type subentity

feat: Mgu/us141391 ta166882 new timing UI

---

src/activities/discussions/DiscussionForumEntity.js
src/activities/discussions/DiscussionForumsEntity.js
src/hypermedia-constants.js

* Added `forumsHref` to `DiscussionForumEntity` (individual)
* Added `DiscussionForumsEntity` (collection)
* Added `create-forum` action
[US142491](https://rally1.rallydev.com/#/?detail=/userstory/644998737805&fdp=true): [ui] Create change forum dialog

US142491 Add create forum action

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js

[US142821](https://rally1.rallydev.com/#/?detail=/userstory/645735331867&fdp=true): [api] Create choose forum dialog

US142821 Add categories to topic

---

src/activities/quizzes/timing/QuizTimingEntity.js
src/hypermedia-constants.js
test/activities/quizzes/data/timing/EditableQuizTimingEntity.js
test/activities/quizzes/timing/QuizTimingEntity.test.js

https://rally1.rallydev.com/#/16349626795d/custom/260792024672?detail=%2Fuserstory%2F643174099233
- Renamed some functions previously created for this story
- Added functions for combining logics for the editor & dialog
- Test cases for timing entities containing the new subentity.

Functions for handling new timing editor & timer settings dialog

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingEntity.js
src/ipsis/course-merge/SelectedCourseMergeOfferingCollectionEntity.js

* https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F627720955105&fdp=true
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/37

feat: Select target course for merging

---

src/activities/CategoriesEntity.js
src/hypermedia-constants.js

[US142821](https://rally1.rallydev.com/#/?detail=/userstory/645735331867&fdp=true): [api] Create choose forum dialog
This let's the categories entity parse the new action serialized from here: https://github.com/Brightspace/lms/pull/29199

US142821 Add action to delete previous category and associate to a new category

---

src/activities/CategoriesEntity.js

[US142491](https://rally1.rallydev.com/#/?detail=/userstory/644998737805&fdp=true): [ui] Create change forum dialog
Supports: https://github.com/BrightspaceHypermediaComponents/activities/pull/3151

US142491 getSelectedCategoryHref

---

src/activities/CategoriesEntity.js

[US142821](https://rally1.rallydev.com/#/?detail=/userstory/645735331867&fdp=true): [api] Create choose forum dialog

US142821 Add FACE Discussions specific category association action

---

src/activities/content/ContentFileEntity.js
src/activities/content/ContentServiceFileEntity.js

This is basically a copy of ContentMediaFileEntity, with a couple small changes.
I'll open a second PR after I merge changes to activities/FACE repo to remove the CS-related fields from ContentMediaFileEntity so nothing breaks in the interim
https://rally1.rallydev.com/#/15545164312d/iterationstatus?detail=%2Fuserstory%2F667912687953

Add new ContentServiceFileEntity for FACE

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js

[US145006](https://rally1.rallydev.com/#/?detail=/userstory/668018288065&fdp=true): [ui] Moderator approval

feat: US145006 topic moderator approval

---

src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.test.js

[DE50978](https://rally1.rallydev.com/#/?detail=/defect/671559541549&fdp=true): [New Discussion Creation] > Missing dirty checks

feat: DE50978 fix dirty check for availability dates

---

src/ipsis/course-merge/CourseMergeOfferingEntity.js

https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F631617806559

feat: US138083 - Add merged status

---

src/activities/ActivityUsageEntity.js

[US145143](https://rally1.rallydev.com/#/?detail=/userstory/668227308137&fdp=true): [ui] Edit add to calendar

US145143 Add displayInCalendar for FACE Quizzing as an interim solution

---

src/activities/discussions/TopicGroupSectionRestrictionsEntity.js

[US146324](https://rally1.rallydev.com/#/?detail=/userstory/672768000413&fdp=true): [ui] display summary tile

feat: US146324 add canDeleteRestrictions()

---

src/ipsis/course-merge/CourseMergeOfferingEntity.js

[US145602](https://rally1.rallydev.com/#/?detail=/userstory/671336494693&fdp=true): Course Merge - Unmerge - Add Processing Unmerge tag to UI

US145602: Course Merge - Unmerge - Add Processing Unmerge tag to UI

---

src/activities/discussions/RestrictedTopicTileEntity.js
src/hypermedia-constants.js

[US146324](https://rally1.rallydev.com/#/?detail=/userstory/672768000413&fdp=true): [ui] display summary tile

feat:US146324 add isAllGroups and isAllSections for tile items

---

src/activities/discussions/TopicGroupSectionRestrictionsEntity.js

[US146332](https://rally1.rallydev.com/#/?detail=/userstory/672776225107&fdp=true): [ui] delete restriction

feat: US146332 add equals to allow dirty checking

---

src/activities/discussions/GroupSectionRestrictionActionsEntity.js
src/activities/discussions/TopicGroupSectionRestrictionsEntity.js
src/hypermedia-constants.js

[US146334](https://rally1.rallydev.com/#/?detail=/userstory/672777856045&fdp=true): [ui] update restriction type

feat: US146334 add group restriction actions

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

[US145143](https://rally1.rallydev.com/#/?detail=/userstory/668227308137&fdp=true): [ui] Edit add to calendar

US145143 Get readonly value of Display in Calendar

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeRootEntity.js

Cleanup based on https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/586#discussion_r1069841437

fix: Update ipsis Rels to match Classes and Actions

---

src/ipsis/course-merge/BaseCollectionEntity.js
src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

Clean up for comment in previous PR: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/586#discussion_r1074015361
[US137422](https://rally1.rallydev.com/#/?detail=/userstory/630445645669&fdp=true): Course Merge-UI-Select to Unmerge Courses
* Tested using https://github.com/Brightspace/ipsis-sis-course-merge/pull/61
* Main course list was able to load and can load more
* Merged courses list was able to load

fix: US137422 - Commonize IPSIS paging methods

---

.github/workflows/prchecklist.yml

Ref: https://github.com/Brightspace/third-party-actions-config/pull/879

build: workflow adjustments for updated 3pa/github-script

---

src/hypermedia-constants.js

New rels to support refactored paged activity collection to improve perf in FACE quizzes.
[US148212](https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Ftask%2F684877386151) [ui] Show questions in FACE Quiz

US148212 TA171324 New rels required for paged activity collections

---

src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js

fix: Fix `originalSourceCourseMergeOfferings`

---

src/es6/SirenAction.js
src/ipsis/course-merge/CourseMergeRootEntity.js

[US137422](https://rally1.rallydev.com/#/?detail=/userstory/630445645669&fdp=true): Course Merge-UI-Select to Unmerge Courses
* https://github.com/Brightspace/lms/pull/33116
* https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/601
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/75

US137422 - Append hidden fields for courseMergeMergedOfferingAction

---

src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

- [DE51954](https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fdefect%2F685087915805&fdp=true&previousTokens=%2F255540250444d%2Fiterationstatus%3Fdetail%3D%252Fdefect%252F685087915805%26view%3Dd1410d32-699b-4f88-b16a-1ae7613f7cba&project=%2Fproject%2F255540250444&ref=%2Fdefect%2F685087915805)
- Adding hasCourseMergeOfferingsHref function for use in [this PR](https://github.com/Brightspace/ipsis-sis-course-merge/pull/73)
- Related PRs: https://github.com/Brightspace/ipsis-sis-course-merge/pull/73 https://github.com/Brightspace/lms/pull/33053

Add hasCourseMergeOfferingsHref function

---

src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js

- [US136496](https://rally1.rallydev.com/#/255540250444d/backlog?detail=%2Fuserstory%2F627721699361&fdp=true)
- Context of PR: https://github.com/Brightspace/ipsis-sis-course-merge/pull/58#discussion_r1099159366 https://github.com/Brightspace/ipsis-sis-course-merge/pull/58#discussion_r1099140426

Add updateEntity and selectedCount to CourseMergeMergedOfferingCollectionEntity

---

src/ipsis/course-merge/CourseMergeOfferingEntity.js

[US146577](https://rally1.rallydev.com/#/?detail=/userstory/673475675019&fdp=true): Course Merge - UI - Display course has content and/or user progress tags in course list
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/83

feat: Add method for Has Content warning feature

---

src/activities/quizzes/timing/QuizTimingEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/?detail=/userstory/685231875221&fdp=true

US148531: Add `isRecommended`, `isAutoSubmit` and `isMarkedExceededTime` methods to `QuizTimingEntity`

---

src/activities/quizzes/timing/QuizTimingEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/685231875221&fdp=true

US148531: Add a null check for isMarkExceeded function

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js
src/ipsis/course-merge/SelectedCourseMergeOfferingsCountEntity.js

[DE51921](https://rally1.rallydev.com/#/?detail=/defect/684873585815&fdp=true): Course Merge - # Selected value is wrong after search/filter
* https://github.com/Brightspace/lms/pull/34258
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/78

feat: Add selected offerings counter entity

---

src/activities/quizzes/timing/QuizTimingEntity.js

https://rally1.rallydev.com/#/?detail=/userstory/691297935487&fdp=true

fix: Add a null check to the `isSync` and `isAsync` function

---

src/activities/quizzes/QuizEntity.js
src/activities/quizzes/timing/QuizTimingEntity.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/timing/EditableQuizTimingEntity.js
test/activities/quizzes/timing/QuizTimingEntity.test.js

https://rally1.rallydev.com/#/16349626795d/custom/260792024672?detail=%2Fuserstory%2F652501704025

US143776 add start types

---

src/entityAddons/describable-entity-mixin.js
src/entityAddons/named-entity-mixin.js

Few more not in the `mixins` folder.

feat: dedupe a few more mixins

---

src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

[US144861](https://rally1.rallydev.com/#/?detail=/userstory/666114564759&fdp=true): (Course Merge) - Message when there are no search results
* https://github.com/Brightspace/lms/pull/35027
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/95

feat: Add isfiltered property getter to entity

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/?detail=/userstory/686647238289&fdp=true
Add completion critera get and set methods, also add completion criteria to the save and dirty checks
https://github.com/BrightspaceHypermediaComponents/activities/pull/3852
https://github.com/Brightspace/lms/pull/35470

US149072 > Completion Component > Hook up new actions to web component

---

README.md

Triggering release for related PR
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/624

feat: whitespace to trigger new version

---

src/activities/ActivityUsageEntity.js

- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fhierarchicalrequirement%2F673975269423
> **Summary of what it is**
> For LTI type activities (both LTI 1.1 and LTI 1.3), add a 3rd completion criteria 'When LTI returns completion' radio button to the component.
> This is behind the flag 'F20654-Allow-LTI-Completion-Return'
>  
>  
> **Design Details**
> ![image](https://user-images.githubusercontent.com/89945180/234981127-34883dbd-a738-46d3-97b2-f69bf781702e.png)
>  
>  
> **Acceptance Criteria**
> 1) Based on the work done for Completion Criteria in F20558, add the 3rd completion criteria to the backend
> 2) Update the Completion Criteria component to display the 'When LTI returns completion' option. This will only appear when feature flag …

US146898 - Add new option for LTI link completion

---

src/activities/quizzes/QuizEntity.js

[US153285](https://rally1.rallydev.com/#/?detail=/userstory/702920056763&fdp=true): Integrate API and UI
Add property to check if negative grading is enabled.

add enable check

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

[US152184](https://rally1.rallydev.com/#/?detail=/userstory/699540183281&fdp=true): [api/ui] Delete compound activity
The delete action lives in the activity-usage entity.

US152184 add function to delete activity instance

---

src/hypermedia-constants.js

Rally Story: https://rally1.rallydev.com/#/?detail=/userstory/673649601925&fdp=true
Adding a rel and actions for Content Styler's new webcomponent and HM API.

feat: Jprouse/us146745 add content styler rel and actions

---

src/hypermedia-constants.js

[US154016](https://rally1.rallydev.com/#/?detail=/userstory/704807766953&fdp=true): [ui] Render add content dialog
Add action name

US154016 add action name

---

src/hypermedia-constants.js

Rally Story: https://rally1.rallydev.com/#/?detail=/userstory/719093211953&fdp=true
Added my actions to the Classes export instead of Actions in a previous PR. I'm also adding the classes this time.

US156129 - move classes to actions, and add real classes

---

src/activities/content/ContentLorActivityEntity.js

- https://rally1.rallydev.com/#/668026692137d/teamboard?detail=%2Fuserstory%2F675232602063
> Acceptance Criteria:
> 
> 1) Clean-up code to stop looking for the feature flag and only use the **TRUE**behaviour 
> 
> 2) Remove the **FALSE**behaviour
> 
> 3) Remove the Feature Flag
> 
>  
> 
> Flag in question:
> 
> <https://github.com/Brightspace/lms-launch-darkly-flags/blob/master/features/activities/face/content/content-lor-scorm-activities.feature.json>
Deleting feature flag in question.

US147084 - Clean-up Flag content-lor-scorm-activities

---

src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

[US152718](https://rally1.rallydev.com/#/?detail=/userstory/701026887461&fdp=true): Course Merge - UI - Allow users from multiple SIS to merge

feat: US152718 - Cleanup userOwnedByMultipleSourceSystems usage

---

src/ipsis/course-merge/BaseCollectionEntity.js
src/ipsis/course-merge/CourseMergeLogDetailCollectionEntity.js
src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingBaseCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

[US154265](https://rally1.rallydev.com/#/?detail=/userstory/705253427401&fdp=true): Course Merge - Audit Log UI- Paging
Related PR(s):
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/152

Add paging to audit table entity

---

src/ipsis/course-merge/CourseMergeLogDetailCollectionEntity.js

Rally Story:
[US136500](https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F627722056821) : Course Merge - UI - Filter the audit log by action, department, and status
Related PR(s):
- https://github.com/Brightspace/lms/pull/42427

feat: US138169  Course Merge - Audit Log UI- Filters

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeLogDetailCollectionEntity.js

[US160501](https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F731674790577&view=d1410d32-699b-4f88-b16a-1ae7613f7cba): Course Merge - UI - Filter the audit log by timeframes
**Related PRs:**
- https://github.com/Brightspace/lms/pull/43020

US160501: Course Merge - Audit Log UI - Time Filter

---

src/es6/SirenAction.js
src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeLogDetailCollectionEntity.js

[US160408](https://rally1.rallydev.com/#/?detail=/userstory/731504783825&fdp=true): Course Merge - Audit Log API/UI - Implement sorting by start time
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/169
* https://github.com/Brightspace/lms/pull/44317

feat: [US160408] - Add course merge sort functions

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeLogDetailEntity.js

* [US160701](https://rally1.rallydev.com/#/?detail=/userstory/732027137913&fdp=true): Course Merge Log - Re-add user column
* https://github.com/Brightspace/lms/pull/44499
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/168

US160701: Course Merge Log - Re-add user column

---

src/activities/quizzes/QuizEntity.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js

https://rally1.rallydev.com/#/?detail=/defect/734509007647&fdp=true

DE56403: remove old "disableRightClick" code

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-236

feat: add content subEntity to activity usage

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-237
Adds `contentModuleName` property which will be displayed in the idea generation dialog
Adds links to file-getting endpoints

feat: fed-237 add contentModuleName property

---

src/activities/content/ContentHtmlFileEntity.js

making a change to re-trigger release

making a change to re-trigger release

---

src/activities/content/ContentHtmlFileEntity.js

fix: re-triggering release

---

package.json
src/activities/content/ContentCompletionEntity.js
src/activities/content/ContentFileEntity.js
test/activities/content/ContentHtmlFileEntity.test.js

US : https://desire2learn.atlassian.net/browse/IDCS-31
Comparing changes in Description field to display cancel modal.

feat: [IDCS-31] adding description equality check in contentfileentity

---

src/activities/content/ContentHtmlFileEntity.js

re-triggering release for https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/699

feat: re-triggering release

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-242
Adds functions to update aiHumanOrigin flag for discussion topics

feat: fed-242 add ai-inspired

---

src/activities/ActivityUsageEntity.js

https://desire2learn.atlassian.net/browse/FED-2430
Related:
https://github.com/Brightspace/lms/pull/48245
https://github.com/BrightspaceHypermediaComponents/activities/pull/4468
https://github.com/Brightspace/generate-question/pull/220

fed-2430: add moduleId

---

src/activities/ActivityUsageEntity.js

https://desire2learn.atlassian.net/browse/FED-2430
Related:
https://github.com/Brightspace/lms/pull/48529
https://github.com/Brightspace/generate-question/pull/227
https://github.com/BrightspaceHypermediaComponents/activities/pull/4486

feat: fed2430: add topicId

---

src/activities/ActivityUsageEntity.js

https://desire2learn.atlassian.net/browse/FED-2546
Remove no longer used endpoints.

feat: fed-2546 remove no longer used functions

---

src/activities/content/ContentWebLinkEntity.js
test/activities/content/ContentWebLinkEntity.test.js

US # https://desire2learn.atlassian.net/browse/IDCS-324
Comparing changes in description field to display cancel modal.

IDCS-324 : adding description equality check in weblink entity

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-2590

feat: fed-2590 add aiInspired param on assignment update

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-2765?atlOrigin=eyJpIjoiMzU0MzEwZDlkYzAyNGE5ZjgwMDA3ZTBhYjc1MzU5NTEiLCJwIjoiaiJ9
Pending work from https://github.com/Brightspace/lms/pull/49893
Adds new text and recommend alignments links to assignment entity.

FED-2765 add assignment text and recommended alignment links to entity

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-2765?atlOrigin=eyJpIjoiZTk0YjRkMjRmM2JlNDU4OWI5NmFhNjA5YTcyNWExYjMiLCJwIjoiaiJ9
Add outcomes-term to assignments so we can select the correct lang terms for outcomes related work in assignments. 
Related: https://github.com/Brightspace/lms/pull/49931

FED-2765 add outcomes term to assignments

---

test/activities/content/ContentLTILinkEntity.test.js

https://desire2learn.atlassian.net/browse/IDCS-480

[IDCS 480 UT] Adding unit tests

---

src/activities/assignments/AssignmentEntity.js

https://desire2learn.atlassian.net/browse/FED-2769?atlOrigin=eyJpIjoiMGMyZDA2ZjEzNDcyNGUwNGE4Y2RiZTJhNjU5MzFlMWQiLCJwIjoiaiJ9
Related to (and needs): https://github.com/Brightspace/lms/pull/50470

FED-2769 add assignment text partial href

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/PHNX-1778
Adding the HM PATCH request action to modify the module color
https://github.com/Brightspace/lms/pull/51689
https://github.com/BrightspaceHypermediaComponents/activities/pull/4640

PHNX-1778 > Backend- Persist changes on Save

---

.github/workflows/prchecklist.yml

Replacing Rally with Jira in the PR checklist.

Update prchecklist: Replacing Rally with Jira

---

src/activities/conditions/LegacyConditions.js

https://desire2learn.atlassian.net/jira/software/c/projects/MAN/boards/313?selectedIssue=MAN-2968
FE PR1: https://github.com/BrightspaceHypermediaComponents/activities/pull/4648
FE PR2: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/723
BE PR: https://github.com/Brightspace/lms/pull/51789

Add tag list support to release conditions

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

https://desire2learn.atlassian.net/browse/PHNX-1933
This ticket follows up on PHNX-1778 to clean up the rest of colour/color changes

PHNX-1933 > Color Picker Followup

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

Backport of https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/725
https://desire2learn.atlassian.net/browse/PHNX-1933
This ticket follows up on PHNX-1778 to clean up the rest of colour/color changes

[CERT] PHNX-1933 > Color Picker Followup (#725)

---

package.json

Manually trying to create a release to use for cert

chore(release): 3.1.4 [skip ci]

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-2797?atlOrigin=eyJpIjoiZWRlNTM0YjczNWYwNDE3NzgxMzg3OTM5NzhhNDA0MGIiLCJwIjoiaiJ9
Changes:
- Remove unused instructionsHref and partialHrefs from assignments
Activities PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/4680

FED-2797 clean up assignment urls that are unused and fix outcomes typo

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

Add new properties to get the registry id and the lores endpoint from the LMS backend
story related
https://desire2learn.atlassian.net/browse/FED-3577

FED-3577 Add registry props

---

src/ipsis/course-merge/CourseMergeLogDetailEntity.js

https://desire2learn.atlassian.net/browse/HYRL-1774
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/210

Queued Status - UI - Update the Course Merge Audit Log to have Queue time

---

src/activities/conditions/LegacyConditions.js

https://desire2learn.atlassian.net/browse/MAN-3391

Add tag list tool tip text to properties

---

src/activities/content/ContentScormActivityEntity.js

[EP-1112: Introduction of Description Field](https://desire2learn.atlassian.net/browse/EP-1112)
* SCORM activity entities now have description properties and an accompanying `set` action for richtext description
* N/A
* Needs LMS PR https://github.com/Brightspace/lms/pull/54764 to work
1. https://github.com/BrightspaceHypermediaComponents/activities/pull/4803
2. https://github.com/Brightspace/lms/pull/54764

EP-1112 scorm description properties and set action

---

src/es6/SirenAction.js
src/mixin/entity-mixin-lit.js
src/mixin/save-status-mixin.js

I feel like I'm approaching the 80/20 boundary, so I'm finally going to stop after this.
Maybe...

Fix jsdoc for performLazySirenAction, add templates for mixins

---

src/mixin/entity-mixin-lit.js

Change caused unit test failures here: https://github.com/Brightspace/d2l-rubric/pull/3352

Fix shouldUpdate

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

https://desire2learn.atlassian.net/browse/FED-3810
Add functions needed for study support in FACE quiz

Fed-3810 add study support

---

src/activities/quizzes/QuizEntity.js

Closes: https://desire2learn.atlassian.net/browse/BORG-4037

Add new prop getters to QuizEntity

---

README.md

feat: noop

---

test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

feat:
Add test for aiHumanOrigin property on content modules
https://desire2learn.atlassian.net/browse/FED-4043

Content Modules aiHumanOrigin property

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js

https://desire2learn.atlassian.net/browse/HAI-455

hai-455 add support for showResultsOverview

---

src/activities/content/ContentLorActivityEntity.js

https://desire2learn.atlassian.net/jira/software/c/projects/EP/boards/603?selectedIssue=EP-1232

Fixing a typo to force a feat update

---

src/activities/content/ContentHtmlFileEntity.js
test/activities/content/ContentHtmlFileEntity.test.js
test/activities/content/data/TestContentHtmlFileEntity.js

https://desire2learn.atlassian.net/browse/FED-4136

Add getAiHumanOrigin to html file topics

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js

[HAI-606 - Add check that quiz has <=20 questions](https://desire2learn.atlassian.net/browse/HAI-606)
PRs:
- activities https://github.com/BrightspaceHypermediaComponents/activities/pull/5038
- lms: https://github.com/Brightspace/lms/pull/59600

HAI-606 Add quiz study support compatibility property

---

src/activities/content/ContentModuleEntity.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

feat: Add action and add field to equals compare

feat: add action for setting ai human origin

---

src/activities/content/ContentFileEntity.js
test/activities/content/ContentHtmlFileEntity.test.js

https://desire2learn.atlassian.net/browse/FED-4436
Update test file to include aiHumanOrigin

Add aiHumanOrigin to equals method so we can detect dirty changes 

---

README.md

try an actual fake change to trigger release

feat: forgot prefix for semantic-release

---

.github/workflows/release.yml

~~One second, changing to add this: https://d2l.slack.com/archives/C0RTNDPC2/p1736544451049599?thread_ts=1736540568.279839&cid=C0RTNDPC2~~

Another attempt to publish to npm

---

src/activities/content/ContentFileEntity.js
src/hypermedia-constants.js

- https://desire2learn.atlassian.net/browse/FED-5306
- add `recommendAlignmentsEndpoint` for outcomes gen on html pages
- https://github.com/Brightspace/lms/pull/64688
- https://github.com/BrightspaceHypermediaComponents/activities/pull/5454

FED-5306: add recommendAlignmentsEndpoint for outcomes gen on html pages

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js

https://desire2learn.atlassian.net/browse/FED-5410
Related: https://github.com/Brightspace/lms/pull/65126
Add recommend alignments link to topic entity

FED-5410 add recommend-alignments to topic

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js

The associated action is being defined in this PR:
https://github.com/Brightspace/lms/pull/65959
https://github.com/Brightspace/lms/pull/65959/files#diff-0e60aae9cec0cf730b627b39f9f645f23bdd1f722133771304ce98d4b6b321d4L47

MED-1475: Add the ability to save module object to createspace

---

src/activities/assetProcessor/APAttachedProcessorsCollectionEntity.js
test/activities/assetProcessor/APAttachedProcessorsCollectionEntity.test.js
test/activities/assetProcessor/data/AttachedProcessorsCollection.js

Siren Sdk changes that are a pre-requisite for https://github.com/BrightspaceHypermediaComponents/activities/pull/5620

[MAJ-1816] Adding settings route launch to attached processors

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js

https://desire2learn.atlassian.net/browse/HAI-1619

Hai-1619: add recommendAlignmentsEndpoint to quizzing 

---

package.json

[GAUD-8290](https://desire2learn.atlassian.net/browse/GAUD-8290)
[GAUD-8290]: https://desire2learn.atlassian.net/browse/GAUD-8290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update @open-wc/dedupe-mixin to v2.

---

src/activities/quizzes/QuizEntity.js

https://desire2learn.atlassian.net/browse/HAI-1625
LMS PR: https://github.com/Brightspace/lms/pull/71446
Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/5969

Hai-1625: add outcomes term

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.test.js
test/activities/assignments/data/EditableAssignment.js

https://github.com/BrightspaceHypermediaComponents/activities/pull/6452/files
https://github.com/Brightspace/lms/pull/74057
https://desire2learn.atlassian.net/browse/NIM-5158

NIM-5158 - Get categoryId from groups entity
