src/es6/EntityFactory.js
test/consortium/ConsortiumTokenCollectionEntity.js
test/es6/EntityFactory.html
test/es6/EntityFactory.js
test/index.html

The Siren sdk was eating any errors that the siren entity store was raising which made it impossible to  handle error cases if you were using the entity store.

propegate error values from siren store

---

src/sequences/SequenceEntity.js
test/SequenceEntity/SequenceEntity.js

- Add an `alternateViewerHref` function to the `SequenceEntity` to allow access to the alternate viewer rather than always using Enhanced Sequence Viewer

Add support for an alternate viewer href to the Sequences domain

---

src/mixin/siren-fetch-mixin-lit.js

Based on https://github.com/BrightspaceHypermediaComponents/activities/pull/419#discussion_r331129724, we should be bubbling these events through shadow DOM boundaries. This allows parent elements to listen for entities being saved by their children, which is helpful e.g. in the case of a page-wide `d2l-save-status` element.

US110194 Bubble entity-save events

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

These allow fetching and editing of the `instructions` on an assignment entity. There are three different representations of the instructions, all of which are made available:
- `instructionsPlaintext`: self-explanatory, this is the HTML-stripped version of the instructions (not really that useful)
- `instructionsHtml`: HTML version of the instructions for displaying the assignment instructions
- `instructionsEditorHtml`: HTML version of the instructions for usage in editors
An example of the difference between the latter two is that an `{orgUnitId}` string template in the former will show as e.g. "6606", whereas in the latter it will just be "{orgUnitId}".

US110195 Add assignment instructions methods

---

src/activities/assignments/AssignmentEntity.js

Missed this in the last change, but we also need to be able to fetch the `richtext-editor-config` subentity from an assignment, if present.

US110195 Add getRichTextEditorConfig to AssignmentEntity

---

src/activities/assignments/AssignmentEntity.js

Merged the previous version of this a little too quickly - the richtext editor config should be a sub-entity of the richtext instructions entity, not on the assignment itself.

US110195 Modify getRichTextEditorConfig

---

src/activities/ActivityUsageEntity.js
src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

This adds accessors for `dueDate/canEditDueDate/saveDueDateAction` to the generic ActivityUsageEntity, which are required for the activity editor. When working with due dates, we're working with a generic activity (rather than a domain-specific entity e.g. `AssignmentActivityActivityUsage`).

US110582 Add dueDate to ActivityUsageEntity

---

src/activities/ActivityUsageEntity.js

Upon initial load, or for entities without a due date, we can end up trying to call `hasActionByName` on undefined. This fixes that, and also explicitly returns `false` for `canEditDueDate` rather than `undefined` if the user does not have the correct action.

US110582 Fixup logic

---

src/activities/ActivityUsageEntity.js
src/activities/assignments/AssignmentEntity.js
src/es6/SirenAction.js
test/es6/SirenUtilTest.html
test/es6/SirenUtilTest.js
test/es6/SirenUtilTestComponent.js

This is basically a copy of the existing `siren-fetch-mixin-lit`, with the intent of replacing it entirely. (It will be removed entirely in a subsequent PR.) The intent of this ES6 module is to be able to do "Siren things" anywhere - right now limited to just `performSirenAction`, but potentially with more functionality to come. This can then be dropped into any class that extends `Entity`.
One difference between this and `siren-fetch-mixin-lit` is that `SirenAction.performSirenAction` doesn't emit `d2l-siren-entity-save-*` events. An HTMLElement is required to fire these events, and passing it in was weird and blurred the line of what exactly `siren-sdk` does - so instead, consumers of `SirenAction.performSirenAction` will be responsible for their own start/end/error behaviour, which is …

Add SirenAction ES6 module

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

This simply surfaces the current submission type for assignment, the list of submission type options, and a method to update the current submission type. Note that this doesn't include full support for completion type (coming soon), which means that some options (On Paper and Observed in Person) will always use the default completion type of "Automatically on due date".

US110198 Add methods for submission type

---

src/activities/assignments/AssignmentEntity.js

When setting the submissionType to one that doesn't have a completion type, we must set the `completionType` to 0 in the request, otherwise we get a 400 from the LMS (i.e. we always have to set both the submissionType and completionType in the request, "clearing" the latter when it doesn't apply).

US110198 Fixup setSubmissionType

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

This uses the new `start-add-new` workflow to set an initial due date if one isn't already set. This is exposed via the same `setDueDate` method, meaning the consumer is blind to this change, and the `siren-sdk` will either set or update the due date as required.
This also removes a method that returns a Siren action, as this was added in error - `siren-sdk` should not expose Siren objects.

US111410 Add support for adding due date

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

This adds support for completion type values, and slightly modifies how the submission type works - in particular, you should be able to set a submission type without having to also set the completion type - we can silently just set it to the first completion type value as necessary, as a sort of fallback/default.
On the other hand, when setting the completion type, the assumption is that we are _only_ modifying the completion type, i.e. the function is only called when setting a completion type is a valid thing to do.

US111526 Add completion type support

---

src/activities/assignments/AssignmentEntity.js

This configuration is specifically attached to the richtext instructions entity, which means the previous name was overly generic. Strictly speaking, they all come from the same place anyway, but that's not for the consumer to know.

US111610 Fix method name

---

src/mixin/save-status-mixin.js

To be used by BrightspaceHypermediaComponents/activities/components/d2l-activity-editor and BrightspaceHypermediaComponents/organizations/components/d2l-organization-availability-set

Add mixin that fires a custom event to signal siren entity save or fail

---

src/activities/ActivityUsageEntity.js
src/activities/AttachmentCollectionEntity.js
src/activities/assignments/AssignmentEntity.js

This is an entity representation of an attachment collection. Currently, this is only being used in the assignments domain, but the design of this entity is generic enough that it could easily be applied to the activities domain (decisions underway on that). For now, this just gives us the basic abilities we need to show an attachment-picker component, in particular knowing whether or not certain actions are available to the user.

US111949 Add AttachmentCollectionEntity

---

src/activities/ActivityUsageEntity.js

Update the check for can edit of availability dates to check that the specific date entity exists on the addNewEntity entity.

Check if the dateEntity exists on the addNewEntity

---

src/activities/AttachmentEntity.js

This is a (very) generic entity that can represent an attachment on an activity - this only works for link attachments right now, but it will likely be changed/moved/updated/renamed when we tackle file attachments in the near future. (Rather than spending hours trying to predict what things will look like for file attachments, it's easier to just make something that works for links now, and come back to it later for files.)

US112016 Add AttachmentEntity

---

src/es6/Entity.js
test/mixin/entity-mixin-test.js
test/utility/siren-sdk-organization-info-lit.js
test/utility/siren-sdk-organization-info.js

Did you ever have the problem where you wanted to use lit's awesome async states but just didn't have a promise when all the entities have loaded?
Well, now you can use `subEntitiesLoaded()` which is a promise that will load when all the sub entities have loaded. It even deals with multiple levels too!
For example, consider having a component root hypermedia entity be an ActivityUsage. That activity usage turns out to have a collection. This is how we would let litElement know when the list of items has changed after everything has loaded:
```
_onActivityUsageChange(usage) {
usage.onSpecializationChange(NamedEntityMixin(DescribableEntityMixin(SimpleEntity)), (specialization) => {
this._specialization = specialization;
this._name = specialization.getName();
this._description = …
```

subEntity load promise

---

src/activities/AttachmentCollectionEntity.js
src/activities/AttachmentEntity.js

Nothing very exciting here, just adds `canAddFileAttachment` to the attachment collection, and modifies the `href` property of an attachment to work with both files and links.

US112361 Add file attachment methods

---

src/activities/AttachmentCollectionEntity.js

Since we're using the file selector dialog in FACE, it takes care of the actual uploading of files. Once they're uploaded by the dialog, we need to attach the existing temp file to the attachment collection, which can be accomplished via the `add-file` action with a `tempFileId` in the POST body.
This is a followup to #111 - probably should have been included there, but didn't yet know what this would look like.

US112361 Add function to attach temp file

---

src/activities/AttachmentCollectionEntity.js

It turns out, we actually need to specify the file system type wheni attaching existing files - the temp file ID only applies in cases where the user has uploaded directly from their computer, and doesn't include e.g. Shared Files or My Locker. This change reflects a change in the API, where we have to specify either a file, _or_ both `fileSystemType` and `fileId`.

US112361 Update add-file action

---

src/activities/AttachmentCollectionEntity.js

This adds `canAddAudioNoteAttachment` and `addAudioNoteAttachment`, which do as you would expect. This also includes a small refactor to break out some common code, since there are really only two types of attachments:
Files:
- file attachment
- video note attachment
- audio note attachment
Links:
- URL attachment
- Google Drive attachment
- OneDrive attachment
The helpers added here centralize a bit of the logic common to each of these groupings.

US111909 Add actions for audio notes

---

package.json
src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js
test/activities/assignments/AssignmentEntity.html
test/activities/assignments/AssignmentEntity.js
test/activities/assignments/data/EditableAssignment.js
test/activities/assignments/data/NonEditableAssignment.js
test/utility/test-helpers.js

Previously we were saving all properties individually which was very chatty. This uses the existing 'PUT' action that was developed for activity feed to save multiple properties in a single API call.
However, i override the action.method to be 'PATCH' which is what the API also supports on the backend, because the PUT implementation also requires a name to always be present, but other than that it basically behaves like a PATCH. I'm going to update the method on the action in the API on a subsequent PR.
In this PR only being used for name & instructions. Will add other fields later.
Also introduced `fetch-mock` library to make mocking siren action calls easier.
Refactored the existing AssignmentEntity test by moving the siren entities into data files to clean up the tests.

Add new Save method to AssignmentEntity for use by Save/Cancel

---

src/activities/assignments/AssignmentEntity.js

For [US112499](https://rally1.rallydev.com/#/110294864140d/detail/userstory/356264445024)
We need this method for MobX to allow validation of completion types when a user switches submission types. This method is very similar to `completionTypeOptions` but does not do the filtering for the currently selected submission type.

Added method for retrieving all completion type options

---

src/mixin/entity-mixin.js
test/mixin/entity-mixin-test.js

This checks for a valid href and token before fetching anything.  This means that it will no longer fall back to cookie auth, but brings it in line with what the old Polymer behavour does (https://github.com/Brightspace/polymer-siren-behaviors/blob/master/store/entity-behavior.js#L70) and what the Lit version of the mixin does (https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/master/src/mixin/entity-mixin-lit.js#L32).
This fixes an issue with the consortium tabs fetching things twice - once with cookie auth (token is `null`), and again one the token resolver has added the token getter function.  I've gone and proactively fixed a bunch of places that were not passing in a `token` to component that use the `EntityMixin` in `organizations`, `enrollments`, `activities` and …

DE37737 - Check for token and href

---

src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.js
test/activities/data/ActivityUsageEntity.js
test/index.html

[US113166](https://rally1.rallydev.com/#/29180338367d/detail/userstory/362987616496)
I've simplified the saving of the score and grade to just use the existing method/action that was being used to just set the score and add a new grade. There were existing methods which were more aligned to autosave which were geared around being very granular around whether we were setting score, adding to grades, removing from grades etc. But this would have made things much more complicated than necessary to handle the general save case. Also for the general save case we want to pass the `inGrades` flag regardless of whether it has changed because we want the latest state to always reflect what the user was seeing.
Also added tests to prevent updating grades if cannot edit grades.
Also, had to fix up …

add support for score and grade to activity usage aggregate save

---

src/activities/assignments/AssignmentEntity.js

This PR allows siren-sdk to save the submission and completion type status that will be stored in MobX.

Added save for submission and completion types

---

src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.js

Move from 3 separate dates to a single date entity to match the new representation in the activities repo.

Refactor activity-usage dates for new object format

---

src/activities/AttachmentCollectionEntity.js
src/files/FilePreviewLocationEntity.js
src/files/FilesHomeEntity.js
src/hypermedia-constants.js
test/files/FilesHomeEntity.html
test/files/FilesHomeEntity.js
test/files/data/FilePreviewLocationEntity.js
test/files/data/FilesHomeEntity.js

The wrappers include a `FileHomeEntity` which contains a method to execute the action to get the FilePreviewLocation siren entity representing the preview location for a file.
The `FilePreviewLocationEntity` is a simple entity that just exposes the file preview location property.

Add siren sdk wrappers for File Preview Location

---

src/activities/ActivityUsageEntity.js
src/es6/SirenAction.js

Create a new action that combine fields from actions with the same href and method into one action, then calls it.
The change combine the dates and the associate-new-grade PATCH requests to activity-usage into one action/request.

Call activityusage save with combined patch calls

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

For [DE38379](https://rally1.rallydev.com/#/110294864140d/detail/defect/377932041916), added a method to retrieve if an assignment has submissions. 
At the moment the Hypermedia API will never return a `folder-type` entity with the `has-submissions` class because it does not exist in the API. The plan is to rename the `read-only` class when the user HAS permission to edit the entity to `has-submissions` since that is what it was really being used for. Then when the user does NOT have permissions the API will actually respond with `read-only`.
The plan is as follows:
1. add `assignmentHasSubmissions` method to siren-sdk
2. add property in assignment MobX store to retrieve this value along with `read-only`
3. replace the `read-only` class in the hypermedia API with `has-submissions` when …

DE38379 Added assignmentHasSubmissions method to AssignmentEntity.js

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

Continuing work from https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/171
This PR makes the `isAssignmentTypeReadOnly` method check the entity for the assignment type actions rather than relying on the `read-only` class.
Also return the submission type even if the assignment is read only.

DE38379 Update siren-sdk to allow displaying info even when in read only mode

---

src/activities/GradeCandidateEntity.js
src/hypermedia-constants.js
test/activities/GradeCandidateEntity.js

This will enable support for setting the grade category when creating the new grade, by getting the `save` action from the GradeCandidateEntity (which has the category information on it).
The save logic in `ActivityUsageEntity` functions without any changes.

US113746 Add helper to get save action from GradeCandidateEntity

---

src/organizations/OrganizationCollectionEntity.js

Using Edge (42.17134.1098.0) these actions would never be performed. 
Now they are!
https://rally1.rallydev.com/#/357252966636d/detail/defect/365347773396

Yup, Fix edge.

---

src/organizations/OrganizationEntity.js

As explained in [DE38903](https://rally1.rallydev.com/#/15545167705d/detail/defect/388906722124?fdp=true), we don't want the my-courses widget settings around hiding the start and end date on the card to affect the adding of the closed badge, or the behavior around hiding closed courses on the main widget view.  Currently it does both because all three places use the same function (`processedDate`) to get this info, but this function can return `null` depending on the `hideCourseStartDate` and `hideCourseEndDate` values.
In this PR, I add two new functions to get the `beforeStartDate` and `afterEndDate` info separately from the `processedDate` function, so that it's not affected by those widget setting values.
Then I need to update `d2l-organization-date`, `d2l-enrollment-card`, …

DE38903 - Add separate start and end date functions to the OrganizationEntity

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.js

Because the dirty/equals check sits in siren-sdk, the dirty check doesn't know that we were substituting an undefined completionType value with String(0) in activities, so the dirty check always fails. Here, we add a get `completionTypeValue` function to siren-sdk that can be used by both activities code and the siren-sdk dirty/equals check.

DE39197 - add get completionTypeValue function

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js
test/activities/ActivityUsageEntity.js
test/activities/data/ActivityUsageEntity.js

Adds support to get the new `direct-associations` activities href `.../activities/{activityId}/usages/{orgUnitId}/associations?direct=1` on the activity-usage entity.
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391870800084

US116718 Support ActivityUsage direct-associations href

---

src/activities/AttachmentCollectionEntity.js

This allows file uploads to work with consistent eval, which expects a single value field

files can be sent as strings

---

src/activities/assignments/AssignmentEntity.js

We should not be trying to find the selected category when the assignment is readonly. It will always be `undefined` since the assignment `setToGroup` action will be missing and so we won't be able to find a selected option from an empty array of groupCategoryOptions.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F399772334476

US117892 - fix readonly assignment type marked as unequal

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.js

The prop is being excluded in the case of submission types that don't support anonymous marking (on-paper and in-person), in which case it should be ignored here.

US118882 Only include isAnonymous in assignment entity dirty check if it is present

---

src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.js

https://trello.com/c/ss2PQ5ho/232-points-string-not-translated-for-assignments-not-originally-in-grades
In support of activities PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/1012

Support getting activity usage gradeType title from unselected numeric gradeType

---

src/activities/assignments/AssignmentEntity.js

Fixes https://trello.com/c/GOrVBGUm/240-notification-email-respect-the-config-d2ltoolsdropboxallownotificationemail
and https://trello.com/c/M1CNW7Kc/241-notification-email-require-permission-assignmentsmanage-delivery
Corresponding changes to lms and activities

add canEditNotificationEmail function

---

src/activities/ActivityUsageEntity.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F405157847512
**Associated PRs**
https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/14588/overview
https://github.com/BrightspaceHypermediaComponents/activities/pull/1033

DE39814 - Stop calling `score-out-of` api if a new grade is created

---

src/activities/ActivityUsageEntity.js

This reverts commit b4c6a59129a9240033e9ed1f636095a37fad5c6e.
That commit added some code to make it safe for the 20.09 release when the server is blue and the UI is green.
But the code can be removed for the 20.10 release.
See Rally for details: https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F411093071188

Revert "Fix to cover BG (green UI / blue server) issues"

---

src/activities/content/ContentEntity.js
test/activities/content/ContentEntity.html
test/activities/content/ContentEntity.js
test/activities/content/data/EditableContent.js
test/index.html

Setting up basic content entity in `siren-sdk` so activities repo can initialize a content store with this entity type. Basing this off a similar approach assignments took when setting up there `assignments-store.js` [here](https://github.com/BrightspaceHypermediaComponents/activities/blob/master/components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-store.js#L7).  Assignments initializes an entity in their state and bases it off the entity definition in this repo. The use of it in the activities repo can be seen [here](https://github.com/BrightspaceHypermediaComponents/activities/blob/master/components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js#L32). 
This is just the initialization of the entity with a basic name property so I can …

Setup basic content entity

---

src/activities/ActivityUsageEntity.js

Issue in save workflow where `toString` is called on `scoreOutOf()` even when it returns undefined. This throws an error and the save workflow is not properly executed. Mitigating this by preventing `toString` being called when `scoreOutOf()` returns undefined.

Don't call toString when scoreOutOf() returns undefined

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/data/EditableQuiz.js
test/activities/quizzes/data/NoneditableQuiz.js

The reason for renaming the `hintsEnabled` constant, is that more quiz subentities are going to be added.
I also renamed the `enabled` string to `checked`. I am working on [US120983](https://rally1.rallydev.com/#/detail/userstory/438844241972?fdp=true) which adds the subentity "DisableRightClick". If DisableRightClick is checked, it can be confusing to include an `enabled` class, likewise a `disabled` class when it is unchecked (i.e. right click not actually disabled).
The backend change is in this PR: https://github.com/Brightspace/lms/pull/3446
Also, disabled could also make it confusing for the future, when someone thinks that class means the checkbox can't be editable or something.

Renaming quiz subentity specific class to be more generic

---

src/activities/quizzes/QuizEntity.js
test/activities/quizzes/QuizEntity.js

The dirty check should be checking the original value of `has-hints` instead of whether we can edit it or not.

Fix quiz hints dirty check

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js
test/activities/content/ContentModuleEntity.js
test/activities/content/data/TestContentModuleEntity.js

Adds delete action to `ContentModuleEntity` so we can call it from the activities UI side when the user cancels the creation of a new module.
**Related PRs**:
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1184
- https://github.com/Brightspace/lms/pull/3414

Add content module delete action

---

.github/workflows/prchecklist.yml

Feedback welcomed! Not sure if we should keep this as an opt-in and add some `if` logic to only target interested parties
**Current reminders:**
- Semver keywords in commit message
- Rally US URL if applicable

Add PR reminder checklist

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js
test/activities/ActivityUsageEntity.js
test/activities/data/ActivityUsageEntity.js

US122312
```Context```
Learning paths is adding a create-form link to redirect new activity usages to the different variation of the edit page. Siren-sdk activty entity needs to support the create-form rel.
https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F455165215100
```Quality```
Unit tests added to validate positive and negative response from createFormHref()

support create-form link

---

src/activities/content/ContentEntity.js
src/activities/content/ContentHelperFunctions.js
src/activities/content/ContentModuleEntity.js
src/activities/content/ContentWebLinkEntity.js
src/hypermedia-constants.js
test/activities/content/ContentEntity.js
test/activities/content/ContentWebLinkEntity.html
test/activities/content/ContentWebLinkEntity.js
test/activities/content/data/TestContentEntity.js
test/activities/content/data/TestContentWebLinkEntity.js
test/index.html

**NOTE:** I am on a new team starting on Jan 4th and would appreciate if someone could take over this PR for me. I'd be more than happy to help with clarification and add feedback where necessary but would be good if someone else could address the improvements/fixes necessary to get this merged.
Aligning siren-sdk with new work Dave Harris has added in the back-end [here](https://github.com/Brightspace/lms/pull/4949#event-4141743719). Adding all classes, properties and actions as defined so we can later access them in the activities repo.
Rally ticket: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F463420383076

Add web-link definition to siren-sdk

---

src/organizations/OrganizationEntity.js

[Rally Defect Link - DE41781](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fdefect%2F465993045240&fdp=true)
When editing a course's description, pressing enter creates a new \<p> element, and separates the previous and new \<p> elements with a newline.
On the other hand, pressing shift+enter creates a new \<br /> element, which is sandwiched (i.e. no whitespace) between the previous and the next word.
Currently, HTML tags are stripped from the description by regex replace: `description.replace(/<[^>]*>/g, '');`. Once this happens, \<p> elements are removed but the newline is left behind to continue separating the previous and next paragraph. However, \<br> elements are removed without leaving behind any whitespace to separate words.
This was fixed by doing a …

Replacing <br> tags with '\n' in description

---

src/activities/quizzes/QuizEntity.js

Fixes https://trello.com/c/Bg8eQ5Xy/302-new-html-editor-cannot-clear-the-content-from-the-description-field

fix: save empty quiz description

---

src/activities/quizzes/timing/QuizTimingEntity.js
test/activities/quizzes/timing/QuizTimingEntity.js

Missed one setter earlier. This one is for toggling the "show clock" checkbox on recommended time.
[US123360](https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F464625055264&fdp=true?fdp=true): [ui] Timing: Render dialog body for Timing Options
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F464625055264&fdp=true?fdp=true

US123360 added showClock setter

---

src/activities/quizzes/timing/QuizTimingEntity.js
test/activities/quizzes/timing/QuizTimingEntity.js

With optimistic rendering, both enforced and recommended entities and this "uselatelimit/automaticzero" entity is always included. So we must determine whether to show it based on whether the enforced timing entity type has the class, rather than the presence of the sub-entity.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F464625055264%2Ftasks

US123360 - Update how automatic-zero is detected

---

src/activities/quizzes/QuizEntity.js

The reason for changing the recently added `headerHtml` and `descriptionHtml` functions is that the functions return booleans instead of undefined. When a quiz entity which does not have these entities, such as a working copy, calls the `equals` function, the header and description data passed to the `equals` function is `false`, while it compares against `this.descriptionEditorHtml()` and `this.headerEditorHtml()` which will return undefined as the header and description entities do not exist.
Changing `_canCheckin` to not be marked private as it will be called by the `activities` repo.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478606416460%2Ftasks

US123692 - changes to support working copy dirty check

---

src/activities/quizzes/timing/QuizTimingEntity.js

When quiz timing properties are changed, return an updated quiz timing entity.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F464625055264%2Ftasks
See usage: https://github.com/BrightspaceHypermediaComponents/activities/pull/1553

US123360 - On update return an updated Quiz Timing entity

---

src/activities/quizzes/QuizEntity.js
test/activities/quizzes/data/EditableQuiz.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F502226480152
The working copy IP entity doesn't have a class so need to fetch based on rel.
Looks something like:
```
{
"rel": [
"https://quizzes.api.brightspace.com/rels/ip"
],
"href": "https://74728563-1618-4c49-s5b6-ddb108a6c965.quizzes.api.dev.brightspace.com/123504/quizzes/1602/ip?workingCopyId=6cdc390b-a8bd-4ec0-8126-22affa9e47ea"
}
```

Getting IP href based on rel instead of class

---

src/es6/SirenAction.js

A base quiz entity contains a checkout action with a quiz href. After POSTing to it, the response is the working copy entity that ends with a workingCopy queryParam. Wtihout my change, the EntityStore was updating the base quiz entity with the returned working copy entity, when in fact, it should be adding a new object to the entity store with the self href of the returned working copy entity.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478606416460%2Ftasks

US123692 - Fix EntityStore updating incorrect entity

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js

This is part of the initiative to retire the Quiz Introduction field that used to exist in the legacy quiz editor. In FACE the introduction field doesn't exist, so for existing quizzes with content in the Introduction quiz we want to append that to the Description field and warn users that the intro field content has been moved and whatever that was invisible could be visible to students now.
* Added `intro-is-appended-to-description` to hypermedia constants
* Checked if quiz entity contains the class `intro-is-appended-to-description`
* If the class is there -> we treat it as the quiz description has changed so that the merged desc + intro could be saved
* If the class isn't there -> proceed with regular checks
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F480 …

US123841 format siren action based on intro is appended to description class

---

src/activities/quizzes/QuizEntity.js

For the activity component to know that the checkin failed because of a server error, we need to reject the promise here instead of silently returning.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478606416460%2Ftasks

US123692 - Return rejected promise if checkin fails (server error)

---

src/activities/quizzes/ipRestrictions/QuizIpRestrictionsEntity.js

If IPs were ever loaded from LMS as `undefined` weird things happened...

Default IPs to empty strings to prevent weird errors

---

src/activities/quizzes/ipRestrictions/QuizIpRestrictionsEntity.js

This check is needed as without it, if a user changes the order of restrictions in local state, it won't realize that they are existing restrictions and will try to save them again in which case the server will flag them as duplicates. An alternative would be to remove that check server side but then we still fire off a bunch of unnecessary network requests. This uses the existing siren-sdk state to as a source of truth for what has already been persisted. If an IP from MobX is present in siren's state, regardless of the order, it should not be sent again.

Check if restriction has already been persisted

---

src/activities/ActivityScoreOutOfEntity.js
src/activities/ActivityUsageEntity.js
test/activities/ActivityScoreOutOfEntity.html
test/activities/ActivityScoreOutOfEntity.js
test/activities/data/ActivityScoreOutOfEntity.js
test/index.html

- New function `scoreOutOfHref()` gets the href if the score-out-of sub-entity is a linked entity (i.e. will be used to display total quiz points)
- Created new `ActivityScoreOutOfEntity` class 
- Added a simple test
[US125529](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F505601651720&fdp=true?fdp=true): [ui] Display total points for a quiz
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F505601651720&fdp=true?fdp=true

US125529 added ActivityScoreOutOfEntity to activity usage

---

src/activities/ActivityUsageEntity.js

On the Content FACE pages, we use the generic `activity-usage`, however our entities have no concept of grades or scoreoutof. As a result, our FACE pages were erroring out and dates were not working.  
This pr adds more aggressive null checking so we are not trying to get properties off of something that does not exist.
https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F511812392384&fdp=true

DE42885: Add more null checking on the scoreoutof entity

---

src/activities/ActivityUsageEntity.js

Modified the `fetchLinkedScoreOutOfEntity` method to take a `bypassCache` param. We want to bypass the cache when refreshing the Total Points component on FACE Quiz when an individual question is edited. 
**Related PRs:**
`hmc`: https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/150
`activities`: BrightspaceHypermediaComponents/activities#1624
[US126109](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F512322551332&fdp=true?fdp=true): Refresh total points on edit
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F512322551332&fdp=true?fdp=true

US126109 modifyed fetchLinkedScoreOutOfEntity to take bypassCache param

---

src/activities/content/ContentWebLinkEntity.js

So this really pertains to #285 , which I forgot to mark with a semver keyword on merge.
[US124553](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F490369835660&fdp=true?fdp=true): Weblinks > Use working copy during FACE create workflow

feat: added working copy actions to content web link entity

---

src/activities/quizzes/attempts/QuizAttemptsEntity.js

[US123706](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true): [ui] Manage Attempts (Attempts allowed, RIO, Attempt conditions)
`0` is also `false` when evaluated in conditionals, this is currently preventing `0` being set as a value for `min` or `max`

US123706 FACE Quizzes: Attempt Condition update values of 0 are handled correctly

---

package.json
src/activities/content/ContentEntity.js
src/activities/content/ContentWebLinkEntity.js
src/hypermedia-constants.js

[US126672](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F519007142480&fdp=true?fdp=true): Modify activities saveHref to handle new working copy items
Adds a method to retrieve the `lesson-view-page` link from the `ContentEntity`, as well as the `activitiy-usage` link from the `ContentWebLink` entity.
The `lesson-view-page` link will allow the FACE UI to navigate back to the correct topic after saving (especially useful for creating a new topic).
The `activity-usage` link allows the web link to raise an event with the updated activity-usage href value when saving. This is important when committing a new unsaved weblink for the first time as the activity usage href will change and the parent control needs to be aware so it can fetch this updated …

Add a lesson-view-page alt html link to activity-usage entities for content topics

---

package.json
src/activities/assignments/CategoriesEntity.js
test/activities/assignments/CategoriesEntity.js

Part of the fix for [this trello card](https://trello.com/c/PPE1Nhce/364-categories-if-user-has-add-edit-assignment-submission-folders-permission-they-see-read-only-view-they-should-have-the-ability-to).
In the initial implementation I was only using `canEditCategories` to determine a user's interaction with categories but in fact there is a need to check if they can edit categories AND if they can add new categories.

Added new method to check if a user can add categories

---

src/activities/assignments/CategoriesEntity.js
src/hypermedia-constants.js
test/activities/assignments/CategoriesEntity.js
test/activities/assignments/data/EditableCategories.js
test/activities/assignments/data/NonEdtiableCategories.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F516602039000
https://trello.com/c/3nsAWve6/372-when-a-course-has-no-categories-categories-cannot-be-added-in-face
Handling new categories permissions by checking for the "collection" class. Also cleaned up how dirty check is handled here.

Update categories to handle new permissions checks

---

src/activities/content/ContentFileEntity.js

[US116840](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fuserstory%2F393033401500&fdp=true): FACE HTML file - Add HTML field via new HTML editor
[US126672](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F519007142480&fdp=true?fdp=true): Modify activities saveHref to handle new working copy items
Adding method to retrieve the `activity-usage` link from the ContentFileEntity.
Similar to [this PR](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/313), we will need the `activity-usage` link in the content file entity in order to get the updated `lesson-view-page` link, which allows the FACE UI to navigate back to the correct topic in lessons after saving.

US116840: Add method to retrieve activity-usage link from ContentFileEntity

---

src/activities/content/ContentFileEntity.js
test/activities/content/ContentFileEntity.js
test/activities/content/ContentHtmlFileEntity.js
test/activities/content/data/TestContentFileEntity.js
test/activities/content/data/TestContentHtmlFileEntity.js

- [US128071](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fuserstory%2F604152072952&fdp=true?fdp=true): (FE) FACE HTML file - Don't load file usage link if not present, change where to check for type
To handle the fact that we don't want to have a file entity usage link when the file activity is new, we have removed the link from the entity response when it's a new entity. Because of this, we can't rely on the file-type class being on this link, so we've moved it to the entity itself. The SDK needs to be updated to look in the right spot for the file-type class.
The update here is to check the entity's classes rather than the link's classes for a matching type. I also updated this to use a map rather than a series of if-statements. This might sacrifice some readability …

US128071 - get file type class from entity

---

src/files/FileEntity.js

[DE43500](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F603973776280&fdp=true): FACE HTML > Head scripts are duplicated when saving html files
A new endpoint was added to the files response which returns the raw file data. We need to access this endpoint in order for it to be consumed in activities when editing html files. We now have two `alternate` links, so they are now being distinguished by their classes.
We need access to the raw data link when editing html files in order to not have the extra head scripts show up in the html editor (a more in depth explanation can be [found in this PR](https://github.com/Brightspace/lms/pull/10645)).
- https://github.com/Brightspace/lms/pull/10645
- https://github.com/BrightspaceHypermediaComponents/activities/pul …

DE43500: Adding getter to raw data endpoint

---

src/activities/ActivityUsageEntity.js

https://trello.com/c/QM0Z876K/335-face-quiz-dirty-check-dialog-is-triggered-for-new-quiz
When scoreOutOf is 0, we convert it to `''` an empty string. So this comparison was failing because it would compare "0" with ''.

Fix dirty check

---

src/activities/associateGrade/AssociateGradeEntity.js

action fields were already handled correctly by performSirenAction, so this was unneeded.

fix: action fields already work

---

src/activities/content/ContentLTILinkFrameOptionsEntity.js

I forgot to squash the commits for PR https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/343 resulting in a failed release (minor increment instead of patch). The original PR is for addressing [DE43998](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F601841380817&fdp=true).
This PR adds a cherry picked commit from master that has a `fix:` keyword to create a patch release.

Trigger patch release: change definition from string to boolean

---

src/activities/associateGrade/AssociateGradeEntity.js
test/activities/associateGrade/AssociateGradeEntity.js

Retrieve the category href. If there is no href, then it is `no category`
Task https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Ftask%2F602375615521&fdp=true?fdp=true
for this story https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069%2Ftasks&fdp=true?fdp=true

US128779 - Get Category Href from create-new entity

---

src/activities/content/ContentFileEntity.js
src/activities/content/ContentHtmlFileTemplatesEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F424774442084
As part of the new Feature work for HTML FACE pages, we would like to support HTML File Template selection. The first piece to this is to fetch the relevant Siren Entities for this, and and display the list of templates in a dropdown menu. (See Rally link for link to designs).
This PR defines the ContentHtmlFileTemplatesEntity class that allows for easier retrieval of HTML File Templates.
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1849

FACE HTML file - Support Template Selection - Dropdown Menu

---

src/activities/content/ContentHtmlFileTemplatesEntity.js
src/files/FileEntity.js

- [US127570](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fuserstory%2F602050357608&fdp=true?fdp=true): FACE HTML file - Support Sorting HTML Templates By Name
We need access to the HTML template entity's title.
Provide a `title()` function on the entity that returns the title and does appropriate null checking.
N/A
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1860
If applicable...

US127570 - update template entity definition to provide a title function

---

src/activities/content/ContentWebLinkEntity.js
src/hypermedia-constants.js

I want to extend the weblink entity to use the working copy entity since they use the same methods (the working copy entity was made after weblink's working copy stuff).
Some code cleanup.
https://github.com/BrightspaceHypermediaComponents/activities/pull/1879

Have weblinks extend working copy entity

---

src/activities/content/ContentFileEntity.js
src/activities/content/ContentHtmlFileEntity.js
test/activities/content/ContentHtmlFileEntity.js
test/activities/content/data/TestContentHtmlFileEntity.js

[DE44237](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F603035824797&fdp=true): `d2l.Tools.Content.FontSize` is not reflecting in content
Now that the content default font size is being returned (added in [this PR](https://github.com/Brightspace/lms/pull/12481)), we need to add the getter in `ContentHtmlFileEntity`. 
I also noticed that `getHtmlTemplatesHref` is in `ContentFileEntity`, so this PR also moves it to `ContentHtmlFileEntity`.
Add getter for the content font size for html files. 
- https://github.com/Brightspace/lms/pull/12481
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1896

DE44237: Add font size property to html entity

---

src/activities/associateGrade/AssociateGradeEntity.js

This helper function was originally made for GET actions with a workingCopyId query parameter because of a bug in SirenAction.js, but we need to push all query params, not just workingCopyId (in particular for grade-candidates endpoint we need the gradeType and includeGradesWithDirectRubrics params)

fix: push all query params to fields, instead of just workingCopyId

---

src/activities/content/ContentScormActivityEntity.js

- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F608173754273
When editing SCORM topics, the discard changes dialog wasn't trigged when updating the title or the external resource property. This PR removes a read-only field from the equality check between two SCORM activity objects.

DE45060: FACE > Editing SCORM activities doesn't trigger discard changes dialog

---

src/activities/ScoringEntity.js

Now the scoreOutOf will be a number type if it's a number, or a string type if it's empty (no score). Comparisons should be made directly without converting numbers to string.

fix: compare score directly without toString

---

src/activities/content/ContentScormActivityEntity.js

Quick commit to add missing `semver` keyword

fix: Get SCORM info from content service

---

src/activities/content/ContentMediaFileCaptionsEntity.js
src/activities/content/ContentMediaFileEntity.js
src/hypermedia-constants.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

Siren representation for captions on content media entities.
lms: https://github.com/Brightspace/lms/pull/15522
activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2111

Show captions from Manage Files on FACE media content page

---

src/activities/content/ContentMediaFileEntity.js
test/activities/content/ContentMediaFileEntity.js
test/activities/content/data/TestContentMediaFileEntity.js

- [US133573](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fuserstory%2F614271395749&fdp=true): Add download option to embedded media view
This PR adds access to the `allowDownload` property in the `ContentMediaFileEntity`, which indicates whether or not to enable the download button in the embedded media player.
Have access to the `allowDownload` property.
- https://github.com/Brightspace/lms/pull/15984
- https://github.com/BrightspaceHypermediaComponents/activities/pull/2139

US133573: add allowDownload method to media file entity

---

src/activities/ScoringEntity.js

https://rally1.rallydev.com/#/?detail=/defect/615608209587&fdp=true
This fixes one small issue where saving "ungraded" did a PATCH on score-out-of endpoint with value "undefined" instead of empty string, which resulted in error.

fix: DE46108 saving no score should be empty string

---

test/activities/CategoriesEntity.js
test/activities/data/EditableCategories.js
test/activities/data/EmptyCategories.js
test/activities/data/NonEdtiableCategories.js
test/activities/data/NonSelectedCategories.js

I was thinking of changing this to `/activities` as categories is now used in multiple tools, however, as Margaret pointed out that doesn't represent a real URL in our system and the actual use of PATCHing categories will be done against a specific tools URL.

Changed URL to tool specific

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.js
test/activities/assignments/data/EditableAssignment.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F618752964661
Apologies for the oversized PR. The root cause of this permissions check is that Assignments was implicitly depending on the `PUT` action which was designed for AF.
[We were overriding the action's method](https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/master/src/activities/assignments/AssignmentEntity.js#L896) inside `save()` which worked provided the `PUT` action was present on the assignment entity itself. 
If the `PUT` action wasn't present then [this check](https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/d9b3c85d7549997b3475fe2f6f84b1d5e6440e31/src/activities/assignments/AssignmentEntity.js#L885) failed and the save became a no-op.
The `PUT` action gets …

Added tests and refactored assignments save to avoid depending on AF specific PUT action

---

src/activities/GradeCandidateEntity.js
src/activities/GradeEntity.js
src/activities/ScoringEntity.js
src/activities/associateGrade/GradeCategoryEntity.js

[DE46153](https://rally1.rallydev.com/#/?detail=/defect/616899740963&fdp=true): FACE Assignment > When choose to link to existing grade item as part of grade category with distributed points, grade out of should not be editable
[DE46154](https://rally1.rallydev.com/#/?detail=/defect/616901920397&fdp=true): FACE Assignment > Updating Grade Out Of value on an assignment linked to a Grade item under grade category with distributed points, doesn't respect the distribution
https://github.com/BrightspaceHypermediaComponents/activities/pull/2248

DE46154 Add Grade Category `maxPoints` and `autoPoints` properties & Grade Candidate `autoPoints` property

---

src/activities/GradeEntity.js
src/activities/ScoringEntity.js
src/activities/associateGrade/GradeCategoryEntity.js

[DE46505](https://rally1.rallydev.com/#/?detail=/defect/620536749613&fdp=true): [cert] FACE Assignment > Updating Grade Out Of value on an assignment linked to a Grade item under grade category with distributed points, doesn't respect the distribution
[DE46506](https://rally1.rallydev.com/#/?detail=/defect/620536751567&fdp=true): [cert] Assignment > When choose to link to existing grade item as part of grade category with distributed points, grade out of should not be editable
Backport of:
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/438

DE46505 & DE46506 [cert] Add grade category max points and auto points properties

---

src/activities/content/ContentLorActivityEntity.js

https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F609370119907
This PR adds the `canEmbed` and `embedUrl` properties that the B/E adds (see below PR)
- LMS: https://github.com/Brightspace/lms/pull/17413
- Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2268

US131809: FACE LOR Links - Display embedded view of object on FACE page

---

src/activities/content/ContentLorActivityEntity.js

- [DE46589](https://rally1.rallydev.com/#/?detail=/defect/620905741399&fdp=true): US131809 Follow-up: LMS & SIren-SDK - Change properties to be links
To better follow the Siren spec, the LOR embedUrl was moved the an `alternate` link instead of a property.
1. LMS: https://github.com/Brightspace/lms/pull/17670

DE46589: Get LOR embedUrl from link instead of property

---

src/activities/associateGrade/AssociateGradeEntity.js

[US134138: SCORM - Push Existing Scores to new Grade Checkbox Displays if New Grade is selected](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F618459351439&fdp=true)
[US134750: SCORM - Push Existing Scores to new Grade Item does the action](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F620808787711&fdp=true)
See various scenarios tested below:
Note that the missing embedded preview is a separate defect and out of scope for this PR.
Diligent user **Studi McStudentface** scored 100% on an imported SCORM topic while it was associated with grade item NC2:
After said topic had its grade association switched to grade item NC1 with the "Push All Existing Scores to Grades" checkbox ticked, Studi's completion was …

US134138: SCORM - Push Existing Scores to new Grade Checkbox Displays if New Grade is selected

---

src/sequences/EndOfSequenceEntity.js

Creates a new representation for the Sequence's End of Sequence Entity. Right now the only thing we need to get from it is the properties from the summary subentity. More stuff can be added to it as it is needed.
https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F622544965323&fdp=true
related sequences pr: https://github.com/BrightspaceHypermediaComponents/sequences/pull/382

Create new end of sequence entity

---

src/activities/ActivityUsageEntity.js

This PR adds a check for the create action on the ActivityAvailabilityDates. We will use this to determine if a user can edit dates in the UI.
1. https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/453
https://rally1.rallydev.com/#/?detail=/userstory/623042532951&fdp=true

feat: Added canEditAvailabilityDates method

---

src/activities/ActivityEvaluationStatusEntity.js
src/hypermedia-constants.js
test/activities/ActivityEvaluationStatusEntity.html
test/activities/ActivityEvaluationStatusEntity.js
test/activities/data/ActivityEvaluationEntity.js

[US136096](https://rally1.rallydev.com/#/?detail=/userstory/626871691749&fdp=true): [UCE] existing completion summary api data source
Adding the `ActivityEvaluationStatusEntity` to be used in the activities repo for the new completion summary component.

US136096 - adding ActivityEvaluationStatusEntity and tests

---

src/activities/content/ContentImportedScormActivityEntity.js

- [DE47321](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F627185737859&fdp=true): Imported SCORM > Embedded preview does not show package on some objects
This PR adds a method for retrieving the alternate link from the imported SCORM siren response to be used in the embedded previews . 
Successfully preview embedded imported SCORM topics on our FACE pages.
- https://github.com/Brightspace/lms/pull/19646
- https://github.com/BrightspaceHypermediaComponents/activities/pull/2412

DE47321: Add embedUrl to imported SCORM entity

---

src/activities/content/ContentImportedScormActivityEntity.js

* https://rally1.rallydev.com/#/289692574792ud/custom/355050439968?Iteration=u&Release=u&c_UXDevKanbanStates=Defined&cpoid=289692574792&detail=%2Fdefect%2F627957174891&rankScope=BACKLOG&typeDef=7362609627
* https://rally1.rallydev.com/#/289692574792ud/custom/355050439968?detail=%2Fuserstory%2F627958967051
Adding a new feature flag, `content-scorm-grade-sync-checkbox` to hide the push-scores-to-grades checkbox on the FACE page.  This affects imported SCORM and can be copied to LOR SCORM as well.
* LD: https://github.com/Brightspace/lms-launch-darkly-flags/pull/3874
* LMS: https://github.com/Brightspace/lms/pull/19755
* Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2422

DE47484 Lessons > SCORM FACE > Hide push to grades checkbox

---

src/activities/ActivityUsageEntity.js

This PR allows the ActivityUsageEntity to submit changes to the FAD date types to hypermedia API for saving.
1. https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/453
2. https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/454
3. https://github.com/BrightspaceHypermediaComponents/activities/pull/2362
4. https://github.com/Brightspace/lms/pull/20022
https://rally1.rallydev.com/#/?detail=/userstory/623042532951&fdp=true

feat: US135527 Added saving for activity FAD date types

---

src/activities/content/ContentLorActivityEntity.js

- [DE44379](https://rally1.rallydev.com/#/?detail=/defect/603904583187&fdp=true): Lessons > 20.21.7.30945 > Modified title to a weblink ends on a content link broken
- LMS: https://github.com/Brightspace/lms/pull/19945
- Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/2431

DE44379: Add prop hasLorInfo to ContentLorActivityEntity

---

package.json
src/activities/associateGrade/GradeSchemeLinkedEntity.js
test/activities/associateGrade/GradeSchemeLinkedEntity.js
test/activities/associateGrade/data/GradeSchemeLinked.js

[DE47339](https://rally1.rallydev.com/#/?detail=/defect/627263379249&fdp=true): Grades > 20.22.1.34790 > Grade Item created in Assignments tool explicitly sets gradeScheme, rather than using the default

DE47339: Add Grade Scheme ID to Linked Entity

---

src/activities/ActivityUsageCollectionEntity.js
src/hypermedia-constants.js
test/activities/ActivityUsageCollectionEntity.html
test/activities/ActivityUsageCollectionEntity.js
test/activities/data/collection.js

* Added method for fetching selected paging type
* Added method for fetching all the available paging type options
* Added equals method to compare entities for dirty check
* Added save method to fire the actual `set-collection-paging` action
* Added unit tests
[US135988](https://rally1.rallydev.com/#/?detail=/userstory/626561954629&fdp=true): [ui] page break options

US135988 Read from and fire set-collection-paging action

---

src/activities/content/ContentLTILinkEntity.js

- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F629905635169
> Design Spec:
> https://xd.adobe.com/view/9848dbf0-ec9e-4831-a276-4ff4f2ec2608-cd1b/screen/97d34b0d-9f0a-4cdc-9563-ad3e8ae53149
> (Note, this design includes a few other items beyond just the banner, this US is only for adding the grey Banner)
> 
> 
> Acceptance Criteria:
> 1) The Grey banner is displayed on the FACE page for LTI Links
> 2) The existing 'Open in New Window' button should be included on the banner (note it's missing in the design but needs to remain on the page)
> 3) If possible, display the name of the LTI is displayed on the banner. If we can't, then continue using 'External Activity'
>     * LTI name isn't the name of the topic, but rather the name of the External …

US137224 LTI - Add Banner with LTI Name

---

src/activities/ActivityUsageEntity.js
src/activities/ScoringEntity.js
src/activities/content/ContentLTILinkEntity.js

- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F631786620271
> Design Spec: https://xd.adobe.com/view/e86e9f24-03cb-405f-89dc-0bad4d31af8f-bd3d/
> 
> Build new Score editor as described [here](https://desire2learn.atlassian.net/wiki/spaces/PHOENIX/pages/3140157869/US137222+SPIKE+-+LTI+-+Determine+how+we+interact+with+LTI+grades#1.-Identify-how-we-want-to-handle-the-grade-component-differences-between-LTI-1.1-and-LTI-1.3-objects.-(ie-is-it-a-separate-FACE-page,-do-we-identify-it-on-load-of-the-page,-etc))
> 
> New component for on the FACE page, identifies number of associated grade items, and includes a button to the multi-grade dialog
> 
> This display needs to be wrapped in a feature flag to control whether grades at all are rendered (on for …

US138199 LTI - Build new LTI Score editor that will handle multiple grades

---

src/activities/AttachmentCollectionEntity.js

[US138621](https://rally1.rallydev.com/#/520974201756d/iterationstatus?detail=%2Fuserstory%2F633260836465&fdp=true&view=3265e82f-7ab0-4a61-abd2-b40776bb4cb3)
Missed semantic release keyword in [last PR](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/480), this is to generate a release (and a minor spacing fix)

US138621 - Add support for OneDrive LTI picker - release

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js
test/activities/discussions/data/NonEditableDiscussionTopic.js

* Added Discussion Topic Entity
* Added functions for fetching and setting name of topic, as well as permission check
* Added tests for the name/title field (Note that the only difference between the two test data files is the presence of `actions`)
[US140433](https://rally1.rallydev.com/#/?detail=/userstory/640968148381&fdp=true): [ui] Edit topic title field

US140433 Add discussion topic entity with name field related functions

---

src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

* [US141251](https://rally1.rallydev.com/#/?detail=/userstory/642767486081&fdp=true): Course Merge - UI - Paging
* https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/505
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/18
This fixes the issue where we'll have loaded 40 of 50 items but it will still say `Load 20 More`. See thread: https://d2l.slack.com/archives/C0PHG3QB0/p1659451002535809?thread_ts=1659125662.045049&cid=C0PHG3QB0

Update pageSize to indicate if less than normal page size

---

test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js
test/activities/discussions/data/NonEditableDiscussionTopic.js

Originally only wanted to add tests for the sync topic and forum name feature but decided to do an overhaul for the existing discussion topic tests. Previously I only added load and permission check for name tests because equals and save functions weren't up yet.
* Added tests for the `equals()` method
* Added tests for the `save()` method
* Added tests for sync topic and forum names (3 different scenarios - happy path, when topic name is unchanged, and when the UI component/mobx flags it as do not sync)
* Refactored description tests as they were added in the wrong place
* Added extra coverage for description entity's read-only properties
[US140926](https://rally1.rallydev.com/#/?detail=/userstory/642120419367&fdp=true): Sync title between new topic + new forum

US140926 Refactor and add tests for discussion topic

---

src/activities/ActivityUsageEntity.js

[DE48783](https://rally1.rallydev.com/#/?detail=/defect/638947673943&fdp=true): [FACE Quiz] > Console errors for PATCH request when start/end/due dates are in invalid states upon saving
Set immediate siren action for validate dates as the caller is awaiting the response anyway and queuing up the action results in an extra unhandled promise error.

fix: DE48783 Set siren action for validateDates to immediate 

---

src/activities/associateGrade/AssociateGradeEntity.js

https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F650301242827
When adding a new grade item with the +Grade Item button, it is possible to add another grade item in the background using the Edit or Link to Existing option and selecting Create and Link to a new grade item. This will add a newly created grade item to the workingcopy but not display in the dialog, allowing it to be saved without knowing. See attached GIF for this behavior.
The goal is to add a new property on the siren entity to allow for activities to determine if an associated grade is associated to an activity
lms: https://github.com/Brightspace/lms/pull/28472
activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/3012

DE50119: LTI multigrades > +Grade Item > 2 grade items associated

---

src/activities/discussions/DiscussionForumsEntity.js

Previously making POST request with empty forum name hence creating "Untitled" forums instead of specified forum name in the dialog
[US142491](https://rally1.rallydev.com/#/?detail=/userstory/644998737805&fdp=true): [ui] Create change forum dialog

US142491 Add POST body data to create forum with specified name

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js

* Added `forumName` getter for read-only view and potentially dirty check
* Added the create and associate with forum action
* Called the action in `save()` when applicable (i.e. when the user has permission and the action field value has changed)
[US142491](https://rally1.rallydev.com/#/?detail=/userstory/644998737805&fdp=true): [ui] Create change forum dialog

US142491 Create new forum and associate current topic with the new forum logic

---

src/activities/discussions/DiscussionForumEntity.js
src/activities/discussions/DiscussionTopicEntity.js

Used wrong Rally story number in commit messages sorry! It should be US142491
The dirty check and save need to be handled centrally within the component because:
1. The topic (`isNew`) and forum (`isParentActivityNew`) states are only available in the front end, so there isn't really a way to preserve the dialog's default selected radio option because it relies on the aforementioned info.
2. The information needed by each of the radio option (input text field and select) are spread across different states (i.e. forum, topic, and categories). Note that when the "create a new forum" option is selected, changes made in the "choose a forum" option's select box should be disregarded for dirty check.
Depending on `isNew`, `isParentActivityNew`, whether save in place has been called before, and …

US142491 Enable individual save actions for discussion forums dialog

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js
test/activities/discussions/DiscussionTopicEntity.test.js
test/activities/discussions/data/EditableDiscussionTopic.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F665853120201
SirenSDK support for participation options. 
Radio options, with three choices: 
- defaultParticipation 
- anonymous
- startThreadToView

US144752: Participation Options

---

package.json
src/activities/ActivityUsageEntity.js
test/activities/ActivityUsageEntity.test.js

https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F671995940833
**Note**: The defect mentions having to save first but it also occurs without saving
A recent addition of the ability to set the availability type (access restricted until available, submission restricted until available etc.) on some FACE pages was introduced and needed to be added to the dirty check as a result.
In the case where the value of `this.defaultStartDateType()` is undefined (i.e most of lessons FACE pages) `this.defaultStartDateType()?.toString()` would return `undefined` as type undefined, not as type string. So left (type undefined) would not actually equal right (type string) in the comparison causing the check to resolve as dirty and trigger the discard changes dialog.
Using …

DE51074: Lessons > discard changes dialog appears after FACE page is saved

---

README.md

Did not include semver keywords in previous 2 PRs, doing whitespace change to trigger a release.
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/557
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/558

fix: Whitespace to trigger release

---

src/activities/content/ContentCompletionEntity.js

Rally Link: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F671674197365
This PR defines the ContentCompletionEntity class to be used by the activities repo for the refactor.
Related PR:
- Activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/3325
- UCE: https://github.com/Brightspace/unified-content-experience/pull/331

feat: US145707: [Continued] UCE -> Move the Manual Completion component to Activities

---

src/activities/discussions/DiscussionTopicEntity.js
src/hypermedia-constants.js

[US146290](https://rally1.rallydev.com/#/?detail=/userstory/672645516489&fdp=true): [api + ui] No groups or sections state
Add check for `no-groups-or-sections` class when a course has no sections or groups. 
[LMS PR](https://github.com/Brightspace/lms/pull/31062)

US146290 add no group or sections class check

---

src/activities/discussions/DiscussionTopicEntity.js
src/activities/discussions/TopicGroupSectionRestrictionsEntity.js

[US146310](https://rally1.rallydev.com/#/?detail=/userstory/672757938285&fdp=true): [api] set up initial working-copy for discussion-topic
Just very basic stuff required for us to be able to call the section-restrictions endpoint from the UI

feat:US146310 add basics for group restrictions

---

src/activities/content/ContentCompletionEntity.js

Rally Link: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F667999409985
This PR updates the class we use to identify manually completable activity types from `manual` (which is also used for tool activity types e.g. assignments and quizzes, which we would not like to support for manual completion) to `requires-user-mark-as-complete`.
Related PR:
- LMS: https://github.com/Brightspace/lms/pull/31376

feat: US144988: [Continued] Add the Manual Completion component to LX

---

src/activities/content/ContentCompletionEntity.js

Change name of class used to determine manual completion component visibility
Backport of: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/566
LMS: https://github.com/Brightspace/lms/pull/31470
BSI: https://github.com/Brightspace/brightspace-integration/pull/8035

DE51360: [CERT] Manual Completion rendering for incorrect ActivityTypes

---

src/activities/quizzes/QuizEntity.js
test/activities/quizzes/QuizEntity.test.js

auto set graded checkbox is now called "Auto-publish attempt results immediately upon completion":
[We are setting the checkbox to true by default if it's a new quiz in FACE](https://github.com/BrightspaceHypermediaComponents/activities/pull/2058) but since this happens after the initial load of quiz entity, new quiz would always be marked as dirty. The idea here is to move dirty check to the component level because the component has information to whether the quiz is new and if save in place has been clicked yet, so it can accurately determine whether the checkbox should be considered dirty.
Related PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/3450
[DE51142](https://rally1.rallydev.com/#/?detail=/defect/672370058493&fdp=true): [New Quiz Creation] > Dirty check …

DE51142 Remove auto set graded checkbox from dirty check for quiz entity

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingEntity.js
src/ipsis/course-merge/SelectedCourseMergeOfferingCollectionEntity.js

This PR includes Renato's changes in https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/585 rather than causing merge conflicts.
[US137422](https://rally1.rallydev.com/#/?detail=/userstory/630445645669&fdp=true): Course Merge-UI-Select to Unmerge Courses
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/61

feat: US137422 - Updates to handle viewing merged course offerings

---

src/activities/content/ContentHelperFunctions.js
src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

https://rally1.rallydev.com/#/?detail=/defect/610830681123&fdp=true
Adding support to retrieve the `raw-description` entity's html to be loaded into the editor. Also want to have dirty check to compare against what is in the db not the replaced version.
https://github.com/Brightspace/lms/pull/32150

DE45495 > Replacement strings not working for modules

---

src/activities/discussions/GroupEntity.js
src/activities/discussions/GroupSectionRestrictionActionsEntity.js
src/activities/discussions/NamedEntity.js
src/activities/discussions/RestrictedTopicCollectionEntity.js
src/activities/discussions/RestrictedTopicEntity.js
src/hypermedia-constants.js

Implement the group list in the Group and Section Restrictions dialog for restricted-topic types:
[US146337](https://rally1.rallydev.com/#/?detail=/userstory/672777987809&fdp=true)

feat: add new entities for restricted topic type

---

src/ipsis/course-merge/BaseCollectionEntity.js
src/ipsis/course-merge/CourseMergeMergedOfferingCollectionEntity.js
src/ipsis/course-merge/CourseMergeOfferingCollectionEntity.js

This fix is part of https://github.com/Brightspace/ipsis-sis-course-merge/pull/65
[DE49910](https://rally1.rallydev.com/#/?detail=/defect/646222579899&fdp=true): Course Merge - Load more doesn't work after search
DE: [DE51900](https://rally1.rallydev.com/#/?detail=/defect/684796230521&fdp=true): Course Merge - Duplicate courses after search
Bug description: 
* The previous page is added to the next page's entity, which leads to duplicate pages after searching and then clearing the search (i.e., returning to the first page without reloading the browser page).

fix: Course Merge broken paging

---

src/activities/discussions/GroupSectionRestrictionActionsEntity.js

remove parent id from being saved when toggleRestrictedTopic is called
[US146337](https://rally1.rallydev.com/#/?detail=/userstory/672777987809&fdp=true)

feat: fix parent id from being saved in toggleRestrictedTopic

---

src/hypermedia-constants.js
src/ipsis/course-merge/CourseMergeRootEntity.js

[US137422](https://rally1.rallydev.com/#/?detail=/userstory/630445645669&fdp=true): Course Merge-UI-Select to Unmerge Courses
* https://github.com/Brightspace/lms/pull/32814
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/68

feat: US137422 - Support action on root entity to navigate directly to merged course

---

src/activities/discussions/GroupSectionRestrictionActionsEntity.js

[DE52094](https://rally1.rallydev.com/#/?detail=/defect/685692839235&fdp=true): Restriction Updates sometimes don't save
In order to await the toggle action we need to return the promise so that we can await it.
Goes with https://github.com/BrightspaceHypermediaComponents/activities/pull/3586

DE52094 return promise from toggle action

---

src/es6/EntityFactory.js
src/mixin/entity-mixin-lit.js

- [US148957](https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F685985340191&fdp=true&view=607e378b-5b78-43dc-a109-b9177724b734)
- The purpose of this PR is to set an error property when an entity cannot be fetched with `EntityMixinLit`
- This will make it possible to catch the case where a user navigates to a route with an invalid org unit, to be redirected to another page

Add _error property to EntityMixinLit

---

src/hypermedia-constants.js
src/organizations/OrganizationEntity.js
src/organizations/userProgress/OrganizationUserProgressEntity.js

[US146577](https://rally1.rallydev.com/#/?detail=/userstory/673475675019&fdp=true): Course Merge - UI - Display course has content and/or user progress tags in course list
* https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/619
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/93
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/109

feat: Add user progress organization entity

---

src/activities/ActivityUsageEntity.js

https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F700141410177
When on the FACE page, we want to disable some `CompletionCriteria` options depending on the state of the `CompletionRequirement`. If the activity is `required`, we will allow all possibilities, but if the activity is `optional`, the only valid state is `Automatic`, so all other options will be disabled. This will allow us to prevent the user from creating possibilities that are not currently supported by the `CompletionTypes` enum.
This is achieved by adding a new list of criteria to pass to the front end. For clarity I renamed the existing list, and used that name for the new one. So going forward:
`AvailableCriteria`: refers to all possibilities the user _could_ choose from, though they …

US152358: Handling not supported completion criteria+ requirement combinations

---

src/activities/content/ContentFileEntity.js
src/activities/content/ContentWebLinkEntity.js
src/hypermedia-constants.js
test/activities/content/ContentFileEntity.test.js
test/activities/content/ContentWebLinkEntity.test.js
test/activities/content/data/TestContentFileEntity.js
test/activities/content/data/TestContentWebLinkEntity.js

Rally Link: [US152524](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F700607131769)
This PR add methods to update the completion criteria by executing the appropriate hypermedia action for files and weblinks.
The actions were added in the LMS [here](https://github.com/Brightspace/lms/pull/36335/files#diff-5fffac92544fb6fe130af06c57c8eac7c97d0938b3ab7332af66127c18f73989R282-R300) and [here](https://github.com/Brightspace/lms/pull/36335/files#diff-3ebfaf0535773a0728b72cfbcd35c2ff808221c0e802a08d4a9b0f1ca023dc08R252-R261)
Related PRs:
LMS - https://github.com/Brightspace/lms/pull/36335
Activities - https://github.com/BrightspaceHypermediaComponents/activities/pull/3904
Note: These changes are specifically being made the way they are to allow for …

US152524: [Front End] Include d2l-activity-content-completion-editor's information in the SAVE action for New Activities

---

src/activities/ActivityEntity.js
src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js
test/activities/ActivityEntity.test.js
test/activities/ActivityUsageEntity.test.js
test/activities/data/ActivityEntity.js
test/activities/data/ActivityUsageEntity.js

[US152381](https://rally1.rallydev.com/#/?detail=/userstory/700183222253&fdp=true): [ui] Edit name for Compound activity
Adds an Activity Entity to represent the activity, which currently contains only a name. I kept the functions general in case we add more sub-entities to the Activity entity, but for now it just has the name.
Assuming the entity returned from the activity endpoint looks like:
```{
"class": ["activity"],
"entities": [
{
"class": [
"activity-name"
],
"properties": {
"name": "Sample Activity Name"
},
"actions": [
{
"href": "https://d53287c1-ad48-4c2e-a0a7-bd53c3029e95.activities.api.dev.brightspace.com/activities/{activityId}",
"name": "update-name",
"method": "PATCH",
"fields": [
{
"type": "text",
"name": "name",
"value": "Sample Activity Name"
}
]
}
]
}
],
"links": [
{ …
```

feat: US152381 create Activity entity which contains activity name

---

src/activities/ActivityEntity.js
src/hypermedia-constants.js
test/activities/data/ActivityEntity.js

[US152381](https://rally1.rallydev.com/#/?detail=/userstory/700183222253&fdp=true): [ui] Edit name for Compound activity
Add rel for activity-name sub-entity. Apparently a rel is required for sub-entities, otherwise the fetch throws errors.

feat: US152381 add rel for activity-name

---

src/activities/discussions/GroupSectionRestrictionActionsEntity.js
src/hypermedia-constants.js

https://rally1.rallydev.com/#/?detail=/userstory/707430937329&fdp=true
These changes are for checking the correct radio button in the dialog `Group and Section Restrictions` according to the `d2l.Tools.Discuss.GroupSectionRestrictionDefault` value
PRs that complements this one are:
- https://github.com/Brightspace/lms/pull/40331
- https://github.com/BrightspaceHypermediaComponents/activities/pull/4156

bbuegare/US155015 Respect config for group and section restriction

---

src/ipsis/course-merge/BaseCollectionEntity.js

[US154265](https://rally1.rallydev.com/#/?detail=/userstory/705253427401&fdp=true): Course Merge - Audit Log UI- Paging
When there are more elements available, we want to show the count as "load 20 more" as we increment the page size by 20. 
Related PR(s):
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/152
* https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/676

fix load more count

---

src/ipsis/course-merge/CourseMergeOfferingEntity.js

[US160699](https://rally1.rallydev.com/#/?detail=/userstory/732026847763&fdp=true): (Course Merge) If section from source course has been deleted from target course, disable source course for unmerge
* https://github.com/Brightspace/lms/pull/44835
* https://github.com/Brightspace/ipsis-sis-course-merge/pull/175

feat: [US160699] - Add sectionDeletedInTarget property

---

src/activities/content/ContentModuleEntity.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

[DE55513](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fdefect%2F729399482859)
This adds the depth as a new property on the content module entity. The dependency PR below uses the depth to figure out the appropriate type of lessons module ( i.e. Unit, Lesson, Folder )
Dependency for this PR:
- https://github.com/BrightspaceHypermediaComponents/activities/pull/4377

feat: DE55513 - add depth to content module entity

---

src/activities/content/ContentCompletionEntity.js

https://rally1.rallydev.com/#/?detail=/defect/734336124523&fdp=true
The manual completion button was being used by content completion and now it is now being used by assigned activities as well, unfortunately in the backend one uses the term `completed` and one uses `complete` , this captures both scenarios without making a change in the backend

DE56374 > Manual Completion Assignments don't show the manual complete button

---

src/hypermedia-constants.js
src/organizations/OrganizationEntity.js

Being added in https://github.com/Brightspace/lms/pull/49836, this does what it says on the tin and links to the Outcomes Settings page for the organization.
https://desire2learn.atlassian.net/browse/MAN-2876

MAN-2876 Add outcome-settings link to OrganizationEntity

---

src/activities/assignments/AssignmentEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-2765?atlOrigin=eyJpIjoiMzU0MzEwZDlkYzAyNGE5ZjgwMDA3ZTBhYjc1MzU5NTEiLCJwIjoiaiJ9
Fix extra calls to `getLinkByRel` (typos) that caused weird behavior where the instructions href was set to the alignments endpoint.

FED-2765 fix alignment links

---

src/activities/AttachmentCollectionEntity.js
src/activities/AttachmentEntity.js

https://desire2learn.atlassian.net/browse/NIM-1824
This allows us to save the attachments immediately if the user on the FACE page chooses to 'Save' and not 'Save and Close'. In the former case, we want the attachments to save/delete immediately so that we can render an accurate representation of what attachments are saved/deleted after the Save occurs.
Dependent PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/4597

NIM-1824 - support immediate flag in add and delete methods for attachments

---

src/es6/Entity.js
src/es6/EntityFactory.js

[GAUD-158](https://desire2learn.atlassian.net/browse/GAUD-158)
This PR updates the `entityFactory` so that it will not invoke the consumer's `onChange` callback when there are `TypeError: NetworkError when attempting to fetch resource.` or `AbortError: The operation was aborted` errors. These errors often occur when the user navigates away while the HM fetches are still in progress. The `onChange` callback often generates an additional error when it tries to use a `null` entity.
[GAUD-158]: https://desire2learn.atlassian.net/browse/GAUD-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reduce the number of errors in Firefox and Safari when navigating while fetching.

---

src/activities/content/ContentModuleEntity.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

[PHNX-1698](https://desire2learn.atlassian.net/jira/software/c/projects/PHNX/boards/341?selectedIssue=PHNX-1698): On Module FACE identify if the accent colour should be visible or not
This PR adds the `customAccentColour` property to the `ContentModuleEntity` entity, introduced in https://github.com/Brightspace/lms/pull/51506.
- https://github.com/Brightspace/lms/pull/51506
- https://github.com/BrightspaceHypermediaComponents/activities/pull/4629
[PHNX-1698]: https://desire2learn.atlassian.net/browse/PHNX-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PHNX-1698: Add customAccentColour to content module entity

---

src/activities/content/ContentModuleEntity.js

https://desire2learn.atlassian.net/browse/PHNX-1778
After changing the backend to require an empty string, we must ensure siren only sends empty strings instead of a string like this "null"

PHNX-1778 > Backend- Persist changes on Save (Fix null)

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-3500
Note: requires https://github.com/Brightspace/lms/pull/52907
Add isAISummaryEnabled to activityUsageEntity to be used by content module editor to decide to show the "generate summary" button.

FED-3500 add isAISummaryEnabled to activityUsageEntity

---

src/activities/content/ContentModuleEntity.js
src/hypermedia-constants.js

https://desire2learn.atlassian.net/browse/FED-3529
Requires: https://github.com/Brightspace/lms/pull/54122 to work.
Updates `setIsAiInspired` to use it's own action (trying to use the description action was not getting sent. Could this be deduping?).
Also fixes logic around if the action should run. Previously it would not run if the desired value was different than the current value which didn't allow it to run at all.

FED-3529 change setIsAiInspired to use new action and fix logic

---

src/es6/Entity.js
src/es6/EntityFactory.js
src/es6/SelflessEntity.js
src/es6/SirenAction.js

I started looking into adding JSDoc to improve VSCode navigation and tooltips. I've been following https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html. Since this is a commonly used library in our projects, this is a useful place to add typing.
If the IDE doesn't support jsdoc/typescript, there would be no effect, and the extra documentation would be useful.

Add typescript jsdoc for better IDE integration

---

src/activities/content/ContentLorActivityEntity.js

[EP-1144: Introduction of Description Field](https://desire2learn.atlassian.net/browse/EP-1144)
- This PR adds changes to the LOR SDK in order to allow for calling and saving description data to the API.
- As I do not have LOR setup locally it is quite hard for me to test these changes.
1. https://github.com/BrightspaceHypermediaComponents/activities/pull/4873 *Front end changes
2. https://github.com/Brightspace/lms/pull/56481 *Backend changes

EP-1144: Update LOR SDK

---

src/activities/quizzes/QuizEntity.js

https://desire2learn.atlassian.net/browse/HAI-453
ShowResultsOverview entity is always included now, even if study support is disabled, so that we can track/set it in the UI immediately when study support is enabled.

feat: hai-453 always include showResultsOverview subEntity

---

src/activities/quizzes/QuizEntity.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js

https://desire2learn.atlassian.net/browse/HAI-762
Adds functionality to persist `suggestContentSelection` value of study support entity.
Related: https://github.com/BrightspaceHypermediaComponents/activities/pull/5139

hai 762 add suggestContent functionality

---

package.json
src/activities/quizzes/QuizEntity.js
src/es6/SirenAction.js
src/hypermedia-constants.js
test/activities/quizzes/QuizEntity.test.js
test/activities/quizzes/data/EditableQuiz.js

https://desire2learn.atlassian.net/browse/HAI-788
Adds functions to allow persisting of remediationCandidates.
Also fixed bug in SirenAction to allow multiple fields with the same name.
Related: 
https://github.com/BrightspaceHypermediaComponents/activities/pull/5177
https://github.com/Brightspace/generate-question/pull/429

hai-788 persist remediation candidates

---

src/activities/assetProcessor/APAttachedProcessorsCollectionEntity.js
src/hypermedia-constants.js
test/activities/assetProcessor/APAttachedProcessorEntity.test.js
test/activities/assetProcessor/data/DeletableProcessor.js
test/activities/assetProcessor/data/DisabledProcessor.js
test/activities/assetProcessor/data/EnabledProcessor.js

https://desire2learn.atlassian.net/browse/MAJ-1931
**Related PRs**
- https://github.com/Brightspace/lms/pull/65776/
- https://github.com/BrightspaceHypermediaComponents/activities/pull/5546
**Changes in this PR**
- Added support for Enabling/Disabling/Deleting Asset Processors using `siren-sdk`
**Local Testing** (can't be testing on a real site
- Install `siren-sdk` and `activities` changes into local BSI
- Attached Processors correctly display "Disable" option in dropdown, when enabled ✔️ 
- Attached Processors correctly display "Enable" option in dropdown, when disabled ✔️ 
- Attached Processors correctly display a disabled status, when disabled ✔️ 
- Attached Processors always display "Delete" option in dropdown (temporary - but expected right now) ✔️ 
- Clicking "Disable" on an …

MAJ-1931 Enable/Disable/"Delete" Processors - Siren SDK

---

src/activities/content/ContentModuleEntity.js
test/activities/content/ContentModuleEntity.test.js
test/activities/content/data/TestContentModuleEntity.js

https://desire2learn.atlassian.net/browse/MAN-3653
With https://github.com/Brightspace/generate-question/pull/527 and https://github.com/BrightspaceHypermediaComponents/activities/pull/5559 there is now no longer a need for the registryId property on module entities.
Will remove it from the LMS once this is merged.

MAN-3653 -- Remove registryId property from module entity

---

src/activities/ActivityUsageEntity.js
src/hypermedia-constants.js
test/activities/ActivityUsageEntity.test.js
test/activities/data/ActivityUsageEntity.js

Add `isAIContentEnabled` to activityUsageEntity to be used by pages to decide whether to show the "modify with AI" button.
Story Related
https://desire2learn.atlassian.net/browse/FED-5892
requires
https://github.com/Brightspace/lms/pull/69313

FED-5892 Add new property to check if AI modify content functionality enabled.

---

src/activities/assetProcessor/APDeepLinksCollectionEntity.js
test/activities/assetProcessor/APDeepLinksCollectionEntity.test.js
test/activities/assetProcessor/data/DeepLinksCollection.js

https://desire2learn.atlassian.net/browse/MAJ-2143
Adding "requires eula" to deeplinking entity to be used when attaching an asset processor

[ MAJ-2143 ] Add Requires EULA to APDeeplinkCollectionEntity

---

src/activities/assignments/AssignmentEntity.js
test/activities/assignments/AssignmentEntity.test.js
test/activities/assignments/data/EditableAssignment.js

https://desire2learn.atlassian.net/browse/MAJ-2141
The API returns a list of submission types that are allowed when asset processors have been attached

maj-2141 - lti - adding allowed submission types for asset processor array
